# messege file
# German translated by toBsucht

#To align text, use the following information: symbol "space" = 4 pixels; symbol "$" = 1 pixel.

# MSG_RETURN_MENU
#Press O to return to the main menu.
!Drücke O, um zum Hauptmenü zurückzukehren.

# MSG_MENU_DATE
#TIME 
!

# MSG_MENU_BATTERY
#battery LifePercent: %3d%% LifeTime:%3d min
!Batterie Prozent: %3d%% Restzeit:%3d min

# MSG_DATE_FMT_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%04d/%02d/%02d  %-10s  %02d:%02d:%02d          
!%04d/%02d/%02d  %-10s  %02d:%02d:%02d          

# MSG_DATE_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%02d/%02d/%04d  %-10s  %02d:%02d:%02d          
!%02d/%02d/%04d  %-10s  %02d:%02d:%02d          

# MSG_DATE_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%02d.%02d.%04d  %-10s  %02d:%02d:%02d          
!%02d.%02d.%04d  %-10s  %02d:%02d:%02d          

# MSG_MAIN_MENU_0
#Graphics and Sound options
!Grafik und Sound Optionen

# MSG_MAIN_MENU_1
#Load state from slot: %d
!Speicher Spielstand aus dem slot : %d

# MSG_MAIN_MENU_2
#Save state to slot: %d
!Speicher Spielstand in den slot   $$: %d

# MSG_MAIN_MENU_3
#Savestate options
!Speicherspielstand Optionen

# MSG_MAIN_MENU_4
#Configure gamepad input
!Konfigurieren gamepad Eingabe

# MSG_MAIN_MENU_5
#Configure analog input
!Konfigurieren analog Eingabe

# MSG_MAIN_MENU_6
#Cheats Manager
!Cheats verwalten

# MSG_MAIN_MENU_7
#Load new game
!Lade neue rom

# MSG_MAIN_MENU_8
#Restart game
!Spiel neustarten

# MSG_MAIN_MENU_9
#Return to game
!Zum Spiel zurückkehren

# MSG_MAIN_MENU_10
#Exit gpSP
!Verlasse gpSP

# MSG_MAIN_MENU_11
#Language and other options
!Sprache und andere Optionen

# MSG_MAIN_MENU_HELP_0
#Select to set display parameters and frameskip behavior,\n
#audio on/off, audio buffer size, and audio filtering.
!\n\n\n
!Wähle to set display parameters and frameskip behavior,\n
!audio on/off, audio buffer size, and audio filtering.

# MSG_MAIN_MENU_HELP_1
#Select to load the game state from the current slot for this game,\n
#if it exists (see the extended menu for more information)\n
#Press left + right to change the current slot.
!\n\n
!Wähle to load the game state from the current slot for this game,\n
!if it exists (mehr Informationen im erweiterten Menü)\n
!Drücke links + rechts to change the current slot.

# MSG_MAIN_MENU_HELP_2
#Select to save the game state to the current slot for this game.\n
#See the extended menu for more information.\n
#Press left + right to change the current slot.
!\n\n
!Wähle to save the game state to the current slot for this game.\n
!mehr Informationen im erweiterten Menü.\n
!Drücke links + rechts to change the current slot.

# MSG_MAIN_MENU_HELP_3
#Select to enter a menu for loading, saving, and viewing the\n
#currently active savestate for this game (or to load a savestate\n
#file from another game)
!\n\n
!Wähle to enter a menu for loading, saving, and viewing the\n
!currently active savestate for this game (or to load a savestate\n
!file from another game)

# MSG_MAIN_MENU_HELP_4
#Select to change the in-game behavior of the PSP buttons and d-pad.
!\n\n\n\n
!Wähle to change the in-game behavior of the PSP buttons and d-pad.

# MSG_MAIN_MENU_HELP_5
#Select to change the in-game behavior of the PSP analog nub.
!\n\n\n\n
!Wähle to change the in-game behavior of the PSP analog nub.

# MSG_MAIN_MENU_HELP_6
#Select to manage cheats.
!\n\n\n\n
!Wähle zum verwalten von cheats.

# MSG_MAIN_MENU_HELP_7
#Select to load a new game (will exit a game if currently playing).
!\n\n\n\n
!Wähle to load a new game (will exit a game if currently playing).

# MSG_MAIN_MENU_HELP_8
#Select to reset the GBA with the current game loaded.
!\n\n\n\n
!Wähle to reset the GBA with the current game loaded.

# MSG_MAIN_MENU_HELP_9
#Select to exit this menu and resume gameplay.
!\n\n\n\n
!Wähle to exit this menu and resume gameplay.

# MSG_MAIN_MENU_HELP_10
#Select to exit gpSP and return to the PSP XMB/loader.
!\n\n\n\n
!Wähle zum verlassen von gpSP und kehre zurück zu PSP XMB/loader.

# MSG_MAIN_MENU_HELP_11
#Languages, set backup behavior, and set device clock speed.
!\n\n\n\n
!Languages, set backup behavior, and set device clock speed.

# MSG_SCALE
#Display scaling: %s
!Display scaling        : %s

# MSG_FILTER
#Screen filtering: %s
!Screen filtering      $$: %s

# MSG_RATIO
#TV output ratio: %s
!TV output ratio       : %s

# MSG_INTERLACE
#TV output interlace: %s
!TV output interlace : %s

# MSG_SKIP_TYPE
#Frameskip type: %s
!Frameskip type      $: %s

# MSG_SKIP_VALUE
#Frameskip value: %d
!Frameskip value     : %d

# MSG_SKIP_RANDOM
#Framskip variation: %s
!Framskip variation : %s

# MSG_AUDIO_ENABLE
#Audio output: %s
!Audio output : %s

# MSG_AUDIO_BUFFER
#Audio buffer: %s
!Audio buffer  $: %s

# MSG_SCREEN_SHOT
#Screen shot
!Screen shot

# MSG_DISPLAY_SCALE
#Scale: %d
!Scale : %d

# MSG_MENU_RETURN_MAIN
#Back
!Zurück

# MSG_G_S_MENU_HELP_0
#Determines how the GBA screen is resized in relation to the entire\n
#screen. Select unscaled 3:2 for GBA resolution, scaled 3:2 for GBA\n
#aspect ratio scaled to fill the height of the PSP screen, and\n
#fullscreen to fill the entire PSP screen.
!\n
!Determines how the GBA screen is resized in relation to the entire\n
!screen. Wähle unscaled 3:2 for GBA resolution, scaled 3:2 for GBA\n
!aspect ratio scaled to fill the height of the PSP screen, and\n
!fullscreen to fill the entire PSP screen.

# MSG_G_S_MENU_HELP_1
#Determines whether or not bilinear filtering should be used when\n
#scaling the screen. Selecting this will produce a more even and\n
#smooth image, at the cost of being blurry and having less vibrant\n
#colors.
!\n
!Determines whether or not bilinear filtering should be used when\n
!scaling the screen. Selecting this will produce a more even and\n
!smooth image, at the cost of being blurry and having less vibrant\n
!colors.

# MSG_G_S_MENU_HELP_2
#Determines what kind of frameskipping should be employed.\n
#Frameskipping may improve emulation speed of many games.\n
#Off: Do not skip any frames.\n
#Auto: Skip up to N frames (see next option) as needed.\n
#Manual: Always render only 1 out of N + 1 frames.
!\n
!Determines what kind of frameskipping should be employed.\n
!Frameskipping may improve emulation speed of many games.\n
!Off: Do not skip any frames.\n
!Auto: Skip up to N frames (see next option) as needed.\n
!Manual: Always render only 1 out of N + 1 frames.

# MSG_G_S_MENU_HELP_3
#For auto frameskip, determines the maximum number of frames that\n
#are allowed to be skipped consecutively.\n
#For manual frameskip, determines the number of frames that will\n
#always be skipped.
!\n
!For auto frameskip, determines the maximum number of frames that\n
!are allowed to be skipped consecutively.\n
!For manual frameskip, determines the number of frames that will\n
!always be skipped.

# MSG_G_S_MENU_HELP_4
#If objects in the game flicker at a regular rate certain manual\n
#frameskip values may cause them to normally disappear. Change this\n
#value to 'random' to avoid this. Do not use otherwise, as it tends to\n
#make the image quality worse, especially in high motion games.
!\n
!If objects in the game flicker at a regular rate certain manual\n
!frameskip values may cause them to normally disappear. Change this\n
!value to 'random' to avoid this. Do not use otherwise, as it tends to\n
!make the image quality worse, especially in high motion games.

# MSG_G_S_MENU_HELP_5
#Select 'no' to turn off all audio output. This will not result in a\n
#significant change in performance.
!\n\n\n
!Wähle 'no' to turn off all audio output. This will not result in a\n
!significant change in performance.

# MSG_G_S_MENU_HELP_6
#Set the size (in bytes) of the audio buffer. Larger values may result\n
#in slightly better performance at the cost of latency; the lowest\n
#value will give the most responsive audio.\n
#This option requires gpSP to be restarted before it will take effect.
!\n
!Set the size (in bytes) of the audio buffer. Larger values may result\n
!in slightly better performance at the cost of latency; the lowest\n
!value will give the most responsive audio.\n
!This option requires gpSP to be restarted before it will take effect.

# MSG_G_S_MENU_HELP_7
#Screen shot
!\n\n\n\n
!Screen shot

# MSG_G_S_MENU_HELP_8
#Return to the main menu.
!\n\n\n\n
!Return to the main menu.

# MSG_G_S_MENU_HELP_9
#TV output ratio
!\n\n\n\n
!TV output ratio

# MSG_G_S_MENU_HELP_10
#Scaling
!\n\n\n\n
!Scaling

# MSG_G_S_MENU_HELP_11
#TV output interlace
!\n\n\n\n
!TV output interlace

# MSG_STATE_MENU_DATE_FMT_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%04d/%02d/%02d  %-10s  %02d:%02d:%02d          
!%04d/%02d/%02d  %-10s  %02d:%02d:%02d          

# MSG_STATE_MENU_DATE_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%02d/%02d/%04d  %-10s  %02d:%02d:%02d          
!%02d/%02d/%04d  %-10s  %02d:%02d:%02d          

# MSG_STATE_MENU_DATE_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%02d.%02d.%04d  %-10s  %02d:%02d:%02d          
!%02d.%02d.%04d  %-10s  %02d:%02d:%02d          

# MSG_STATE_MENU_DATE_NONE_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#----/--/--  ----------  --:--:--          
!----/--/--  ----------  --:--:--          

# MSG_STATE_MENU_DATE_NONE_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#--/--/----  ----------  --:--:--          
!--/--/----  ----------  --:--:--          

# MSG_STATE_MENU_DATE_NONE_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#--.--.----  ----------  --:--:--          
!--.--.----  ----------  --:--:--          

# MSG_STATE_MENU_STATE_NONE
#No savestate exists for this slot.
!          $$Kein sparzustand existiert\n\n
!                   $für diesen slot

# MSG_STATE_MENU_TITLE
#Savestate options:
!Savestate options:

# MSG_STATE_MENU_0
#Load savestate from current slot
!Load savestate from current slot

# MSG_STATE_MENU_1
#Save savestate to current slot
!Save savestate to current slot

# MSG_STATE_MENU_2
#Load savestate from file
!Load savestate from file

# MSG_STATE_MENU_3
#Current savestate slot: %d
!Current savestate slot : %d

# MSG_STATE_MENU_4
#Back
!Zurück

# MSG_STATE_MENU_HELP_0
#Select to load the game state from the current slot for this game.\n
#Press left + right to change the current slot.
!\n\n\n
!Wähle to load the game state from the current slot for this game.\n
!Drücke links + rechts to change the current slot.

# MSG_STATE_MENU_HELP_1
#Select to save the game state to the current slot for this game.\n
#Press left + right to change the current slot.
!\n\n\n
!Wähle to save the game state to the current slot for this game.\n
!Drücke links + rechts to change the current slot.

# MSG_STATE_MENU_HELP_2
#Restore gameplay from a savestate file.\n
#Note: The same file used to save the state must be present.\n
!\n\n\n
!Restore gameplay from a savestate file.\n
!Note: The same file used to save the state must be present.\n

# MSG_STATE_MENU_HELP_3
#Change the current savestate slot.\n
!\n\n\n\n
!Change the current savestate slot.\n

# MSG_STATE_MENU_HELP_4
#Return to the main menu.
!\n\n\n\n
!Return to the main menu.

# MSG_PAD_MENU_0
#D-pad up: %s
!D-pad up          $$$: %s

# MSG_PAD_MENU_1
#D-pad down: %s
!D-pad down       : %s

# MSG_PAD_MENU_2
#D-pad left: %s
!D-pad links       : %s

# MSG_PAD_MENU_3
#D-pad right: %s
!D-pad rechts     : %s

# MSG_PAD_MENU_4
#Cross: %s
!Cross               $$: %s

# MSG_PAD_MENU_5
#Circle: %s
!Circle               : %s

# MSG_PAD_MENU_6
#Square: %s
!Square             $: %s

# MSG_PAD_MENU_7
#Triangle: %s
!Triangle           $$: %s

# MSG_PAD_MENU_8
#Left Trigger: %s
!Linker Trigger  $$: %s

# MSG_PAD_MENU_9
#Right Trigger: %s
!Rechter Trigger : %s

# MSG_PAD_MENU_10
#Start: %s
!Start               $$: %s

# MSG_PAD_MENU_11
#Select: %s
!Wähle               : %s

# MSG_PAD_MENU_12
#Use default map: %s
!Use default map : %s

# MSG_PAD_MENU_13
#Back
!Zurück

# MSG_PAD_MENU_HELP_12
#Use default map
!\n\n\n\n
!Use default map

# MSG_PAD_MENU_HELP_13
#Return to the main menu.
!\n\n\n\n
!Return to the main menu.

#Settings configuration PAD

# MSG_PAD_MENU_CFG_0
#UP
!UP

# MSG_PAD_MENU_CFG_1
#DOWN
!DOWN

# MSG_PAD_MENU_CFG_2
#LEFT
!Links!Links

# MSG_PAD_MENU_CFG_3
#RIGHT
!Rechts!Rechts

# MSG_PAD_MENU_CFG_4
#A
!A

# MSG_PAD_MENU_CFG_5
#B
!B

# MSG_PAD_MENU_CFG_6
#L
!L

# MSG_PAD_MENU_CFG_7
#R
!R

# MSG_PAD_MENU_CFG_8
#START
!START

# MSG_PAD_MENU_CFG_9
#SELECT
!Wähle

# MSG_PAD_MENU_CFG_10
#MENU
!MENU

# MSG_PAD_MENU_CFG_11
#FASTFORWARD
!FASTFORWARD

# MSG_PAD_MENU_CFG_12
#LOAD STATE
!LOAD STATE

# MSG_PAD_MENU_CFG_13
#SAVE STATE
!SAVE STATE

# MSG_PAD_MENU_CFG_14
#RAPIDFIRE A
!RAPIDFIRE A

# MSG_PAD_MENU_CFG_15
#RAPIDFIRE B
!RAPIDFIRE B

# MSG_PAD_MENU_CFG_16
#RAPIDFIRE L
!RAPIDFIRE L

# MSG_PAD_MENU_CFG_17
#RAPIDFIRE R
!RAPIDFIRE R

# MSG_PAD_MENU_CFG_18
#VOLUME UP
!VOLUME UP

# MSG_PAD_MENU_CFG_19
#VOLUME DOWN
!VOLUME DOWN

# MSG_PAD_MENU_CFG_20
#DISPLAY FPS
!DISPLAY FPS

# MSG_PAD_MENU_CFG_21
#NOTHING
!NOTHING

# MSG_PAD_MENU_CFG_HELP_0
#Up button on GBA d-pad.
!\n\n\n\n
!Up button on GBA d-pad.

# MSG_PAD_MENU_CFG_HELP_1
#Down button on GBA d-pad.
!\n\n\n\n
!Down button on GBA d-pad.

# MSG_PAD_MENU_CFG_HELP_2
#Left button on GBA d-pad.
!\n\n\n\n
!Linker Knopf on GBA d-pad.

# MSG_PAD_MENU_CFG_HELP_3
#Right button on GBA d-pad.
!\n\n\n\n
!Rechter Knopf on GBA d-pad.

# MSG_PAD_MENU_CFG_HELP_4
#A button on GBA.
!\n\n\n\n
!A button on GBA.

# MSG_PAD_MENU_CFG_HELP_5
#B button on GBA.
!\n\n\n\n
!B button on GBA.

# MSG_PAD_MENU_CFG_HELP_6
#Left shoulder button on GBA.
!\n\n\n\n
!Linker Schulter Knopf on GBA.

# MSG_PAD_MENU_CFG_HELP_7
#Right shoulder button on GBA.
!\n\n\n\n
!Rechter Schulter Knopf on GBA.

# MSG_PAD_MENU_CFG_HELP_8
#Start button on GBA.
!\n\n\n\n
!Start button on GBA.

# MSG_PAD_MENU_CFG_HELP_9
#Select button on GBA.
!\n\n\n\n
!Wähle button on GBA.

# MSG_PAD_MENU_CFG_HELP_10
#Brings up the options menu.
!\n\n\n\n
!Brings up the options menu.

# MSG_PAD_MENU_CFG_HELP_11
#Toggles fastforward on/off (don't expect it to do much or anything)
!\n\n\n\n
!Toggles fastforward on/off (don't expect it to do much or anything)

# MSG_PAD_MENU_CFG_HELP_12
#Loads the game state from the current slot.
!\n\n\n\n
!Loads the game state from the current slot.

# MSG_PAD_MENU_CFG_HELP_13
#Saves the game state to the current slot.
!\n\n\n\n
!Saves the game state to the current slot.

# MSG_PAD_MENU_CFG_HELP_14
#Rapidly press/release the A button on GBA.
!\n\n\n\n
!Rapidly drücke/release the A button on GBA.

# MSG_PAD_MENU_CFG_HELP_15
#Rapidly press/release the B button on GBA.
!\n\n\n\n
!Rapidly drücke/release the B button on GBA.

# MSG_PAD_MENU_CFG_HELP_16
#Rapidly press/release the L shoulder button on GBA.
!\n\n\n\n
!Rapidly drücke/release the L shoulder button on GBA.

# MSG_PAD_MENU_CFG_HELP_17
#Rapidly press/release the R shoulder button on GBA.
!\n\n\n\n
!Rapidly drücke/release the R shoulder button on GBA.

# MSG_PAD_MENU_CFG_HELP_18
#Increases the volume.
!\n\n\n\n
!Increases the volume.

# MSG_PAD_MENU_CFG_HELP_19
#Decreases the volume.
!\n\n\n\n
!Decreases the volume.

# MSG_PAD_MENU_CFG_HELP_20
#Displays virtual/drawn frames per second.
!\n\n\n\n
!Displays virtual/drawn frames per second.

# MSG_PAD_MENU_CFG_HELP_21
#Does nothing.
!\n\n\n\n
!Does nothing.

# MSG_A_PAD_MENU_0
#Analog up: %s
!Analog up      $$$: %s

# MSG_A_PAD_MENU_1
#Analog down: %s
!Analog down   : %s

# MSG_A_PAD_MENU_2
#Analog left: %s
!Analog links   : %s

# MSG_A_PAD_MENU_3
#Analog right: %s
!Analog rechts : %s

# MSG_A_PAD_MENU_4
#Enable analog: %s
!Enable analog        $$: %s

# MSG_A_PAD_MENU_5
#Analog sensitivity: %d
!Analog sensitivity : %d

# MSG_A_PAD_MENU_6
#Tilt sensor : %s
!Tilt sensor            : %s

# MSG_A_PAD_MENU_7
#Back
!Zurück

# MSG_A_PAD_MENU_HELP_0
#Select 'no' to block analog input entirely.
!\n\n\n\n
!Wähle 'no' to block analog input entirely.

# MSG_A_PAD_MENU_HELP_1
#Determine sensitivity/responsiveness of the analog input.\n
#Lower numbers are less sensitive.
!\n\n\n
!Determine sensitivity/responsiveness of the analog input.\n
!Lower numbers are less sensitive.

# MSG_A_PAD_MENU_HELP_2
#Tilt sensor
!\n\n\n\n
!Tilt sensor

# MSG_A_PAD_MENU_HELP_3
#Return to the main menu.
!\n\n\n\n
!Return to the main menu.

# MSG_CHEAT_MENU_NON_LOAD
#cheat %d (none loaded)
!cheat %d (none loaded)

# MSG_CHEAT_MENU_0
#cheat %d (%s): %%s
!cheat %d (%s): %%s

# MSG_CHEAT_MENU_1
#Load Cheat File
!Load Cheat File

# MSG_CHEAT_MENU_2
#Clock speed: %s
!Clock speed     $: %s

# MSG_CHEAT_MENU_3
#Update backup: %s
!Update backup : %s

# MSG_CHEAT_MENU_4
#Back
!Zurück

# MSG_CHEAT_MENU_HELP_0
#Activate/deactivate this cheat code.
!\n\n\n\n
!Activate/deactivate this cheat code.

# MSG_CHEAT_MENU_HELP_1
# Load Cheat File
!\n\n\n\n
!Load Cheat File

# MSG_CHEAT_MENU_HELP_2
#Change the clock speed of the device. Higher clock speed will yield\n
#better performance, but will use drain battery life further.
!\n\n\n
!Change the clock speed of the device. Higher clock speed will yield\n
!better performance, but will use drain battery life further.

# MSG_CHEAT_MENU_HELP_3
#Determines when in-game save files should be written back to\n
#memstick. If set to 'automatic' writebacks will occur shortly after\n
#the game's backup is altered. On 'exit only' it will only be written\n
#back when you exit from this menu (NOT from using the home button).\n
#Use the latter with extreme care.
!\n
!Determines when in-game save files should be written back to\n
!memstick. If set to 'automatic' writebacks will occur shortly after\n
!the game's backup is altered. On 'exit only' it will only be written\n
!back when you exit from this menu (NOT from using the home button).\n
!Use the latter mit großer Vorsicht.

# MSG_CHEAT_MENU_HELP_4
#Return to the main menu.
!\n\n\n\n
!Return to the main menu.

# MSG_MISC_MENU_0
#Emulate Core : %s
!Emulate Core : %s

# MSG_MISC_MENU_1
#Debug mode : %s
!Debug mode : %s

# MSG_MISC_MENU_2
#Language : %s
!Language : %s

# MSG_MISC_MENU_3
#Fake Fat : %s
!Fake Fat  : %s

# MSG_MISC_MENU_4
#Boot Mode : %s
!Boot Mode : %s

# MSG_MISC_MENU_5
#Brightness : %d
!Brightness : %d

# MSG_MISC_MENU_HELP_0
#Emulate Core
!\n\n\n\n
!Emulate Core

# MSG_MISC_MENU_HELP_1
#Debug mode
!\n\n\n\n
!Debug mode

# MSG_MISC_MENU_HELP_2
#Language
!\n\n\n\n
!Language

# MSG_MISC_MENU_HELP_3
#Fake Fat
!\n\n\n\n
!Fake Fat

# MSG_MISC_MENU_HELP_4
#Boot Mode
!\n\n\n\n
!Boot Mode

# MSG_MISC_MENU_HELP_5
#Brightness
!\n\n\n\n
!Brightness

# MSG_NON_LOAD_GAME
#No game loaded yet
!             $Kein spiel geladen noch

# MSG_WDAY_0
#Sunday
!Sonntag

# MSG_WDAY_1
#Monday
!Montag

# MSG_WDAY_2
#Tuesday
!Dienstag

# MSG_WDAY_3
#Wednesday
!Mittwoch

# MSG_WDAY_4
#Thursday
!Donnerstag

# MSG_WDAY_5
#Friday
!Freitag

# MSG_WDAY_6
#Saturday
!Samstag

# MSG_YES
#yes
!ja

# MSG_NO
#no
!nein

# MSG_YES_NO
#Yes - X / No - O
!Ja - X / Nein - O

# MSG_ENABLED
#enabled
!freigegeben

# MSG_DISABLED
#disabled
!behindert

# MSG_SCALE_UNSCALED
#unscaled 3:2
!unscaled 3:2

# MSG_SCALE_SCALED
#scaled 3:2
!scaled 3:2

# MSG_SCALE_FULL
#fullscreen 16:9
!vollbild 16:9

# MSG_SCN_OPT1
#option 1
!option 1

# MSG_SCN_OPT2
#option 2
!option 2

# MSG_FS_AUTO
#automatic
!automatisch

# MSG_FS_MANUAL
#manual
!handbuch

# MSG_FS_OFF
#off
!aus

# MSG_FS_UNIFORM
#uniform
!uniform

# MSG_FS_RAMDOM
#random
!zufällig

# MSG_SB_2048
#2048 bytes
!2048 bytes

# MSG_SB_3072
#3072 bytes
!3072 bytes

# MSG_SB_4096
#4096 bytes
!4096 bytes

# MSG_SB_5120
#5120 bytes
!5120 bytes

# MSG_SB_6144
#6144 bytes
!6144 bytes

# MSG_SB_7168
#7168 bytes
!7168 bytes

# MSG_SB_8192
#8192 bytes
!8192 bytes

# MSG_SB_9216
#9216 bytes
!9216 bytes

# MSG_SB_10240
#10240 bytes
!10240 bytes

# MSG_SB_11264
#11264 bytes
!11264 bytes

# MSG_SB_12288
#12288 bytes
!12288 bytes

# MSG_BK_EXITONLY
#Exit only
!nur ausgang

# MSG_BK_AUTO
#Automatic
!automatisch

# MSG_CLK_33
#33MHz
!33MHz

# MSG_CLK_66
#66MHz
!66MHz

# MSG_CLK_100
#100MHz
!100MHz

# MSG_CLK_133
#133MHz
!133MHz

# MSG_CLK_166
#166MHz
!166MHz

# MSG_CLK_200
#200MHz
!200MHz

# MSG_CLK_233
#233MHz
!233MHz

# MSG_CLK_266
#266MHz
!266MHz

# MSG_CLK_300
#300MHz
!300MHz

# MSG_CLK_333
#333MHz
!333MHz

# MSG_SS_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%04d_%02d_%02d_%s%02d_%02d_%02d_%03d
!%04d_%02d_%02d_%s%02d_%02d_%02d_%03d

# MSG_SS_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%s%02d_%02d_%04d_%02d_%02d_%02d_%03d
!%s%02d_%02d_%04d_%02d_%02d_%02d_%03d

# MSG_SS_FMT_3
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%s%02d_%02d_%04d_%02d_%02d_%02d_%03d
!%s%02d_%02d_%04d_%02d_%02d_%02d_%03d

# MSG_ERR_BIOS_1
#Sorry, but gpSP requires a Gameboy Advance BIOS image to run\n
#correctly. Make sure to get an authentic one (search the web,\n
#beg other people if you want, but don't hold me accountable\n
#if you get hated or banned for it), it'll be exactly 16384\n
#bytes large and should have the following md5sum value:\n\n
!Sorry, but gpSP requires a Gameboy Advance BIOS image to run\n
!correctly. Make sure to get an authentic one (search the web,\n
!beg other people if you want, but don't hold me accountable\n
!if you get hated or banned for it), it'll be exactly 16384\n
!bytes large and should have the following md5sum value:\n\n

# MSG_ERR_BIOS_2
#a860e8c0b6d573d191e4ec7db1b1e4f6 or 1c0d67db9e1208b95a1506b1688a0ad6\n\n
#Other BIOS files might work either partially completely, I\n
#really don't know.\n\n
#When you do get it name it gba_bios.bin and put it in the\n
#same directory as this EBOOT.\n\n
#Good luck. Press any button to exit.\n
!a860e8c0b6d573d191e4ec7db1b1e4f6 or 1c0d67db9e1208b95a1506b1688a0ad6\n\n
!Other BIOS files might work either partially completely, I\n
!really don't know.\n\n
!When you do get it name it gba_bios.bin and put it in the\n
!same directory as this EBOOT.\n\n
!Viel Glück. Drücke einen Knopf zum verlassen.\n

# MSG_ERR_BIOS_MD5
#This BIOS is not regular.\n
#There is a possibility of various trouble.\n\n
#Please use regular BIOS.\n
!Dies BIOS ist nicht standard.\n
!There is a possibility of various trouble.\n\n
!Please use regular BIOS.\n

# MSG_R_4_3
#ratio 4:3
!verhältnis 4:3

# MSG_R_16_9
#ratio 16:9
!verhältnis 16:9

# MSG_I_NON
#progressive
!progressiv

# MSG_I_ON
#interlace
!verschachteln

# MSG_INIT_END
#Initialization end
!Initialisierung ende

# MSG_LOAD_STATE
#Load State.
!Lastzustand.

# MSG_LOAD_STATE_END
#Load State End.
!Lastzustand End.

# MSG_SAVE_STATE
#Save State.
!Save State.

# MSG_SAVE_STATE_END
#Save State End.
!Save State End.

# MSG_LOAD_STATE_No
#Load State No: %d
!Load State No: %d

# MSG_SAVE_STATE_No
#Save State No: %d
!Save State No: %d

# MSG_LOAD_ZIP_ROM
#Load ZIP ROM.
!Belastung ZIP ROM.

# MSG_LOAD_ROM
#Load ROM.
!Belastung ROM.

# MSG_LOAD_ROM_OK
#Load ROM OK.
!Belastung ROM OK.

# MSG_CHEAT_MENU_5
#Cheat page: %d
!Cheat page : %d

# MSG_CHEAT_MENU_HELP_5
#Cheat page
!\n\n\n\n
!Cheat page

# MSG_CHEAT_MENU_6
#Enable HOME: %s
!Enable "HOME"   : %s

# MSG_CHEAT_MENU_HELP_6
#Enable HOME
!\n\n\n\n
!Enable button "HOME"
