# messege file
# Portugues (Brasil)

#To align text, use the following information: symbol "space" = 4 pixels; symbol "$" = 1 pixel.

# MSG_RETURN_MENU
#Press O to return to the main menu.
!Pressione O para voltar ao menu principal.

# MSG_MENU_DATE
#TIME 
!

# MSG_MENU_BATTERY
#battery LifePercent: %3d%% LifeTime:%3d min
!bateria: %3d%% Tempo de carga: %3d min

# MSG_DATE_FMT_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%04d/%02d/%02d  %-10s  %02d:%02d:%02d          
!%04d/%02d/%02d  %-10s  %02d:%02d:%02d          

# MSG_DATE_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%02d/%02d/%04d  %-10s  %02d:%02d:%02d          
!%02d/%02d/%04d  %-10s  %02d:%02d:%02d          

# MSG_DATE_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%02d.%02d.%04d  %-10s  %02d:%02d:%02d          
!%02d.%02d.%04d  %-10s  %02d:%02d:%02d          

# MSG_MAIN_MENU_0
#Graphics and Sound options
!Opcoes de graficos e som

# MSG_MAIN_MENU_1
#Load state from slot: %d
!Carregar jogo salvo na entrada : %d

# MSG_MAIN_MENU_2
#Save state to slot: %d
!Salvar jogo na entrada            $$: %d

# MSG_MAIN_MENU_3
#Savestate options
!Opcoes de salvamento

# MSG_MAIN_MENU_4
#Configure gamepad input
!Configurar controlador

# MSG_MAIN_MENU_5
#Configure analog input
!Configurar controlador analógico

# MSG_MAIN_MENU_6
#Cheats Manager
!Opcoes de Cheats e diversos

# MSG_MAIN_MENU_7
#Load new game
!Carregar outro jogo

# MSG_MAIN_MENU_8
#Restart game
!Reiniciar jogo

# MSG_MAIN_MENU_9
#Return to game
!Retorne ao jogo

# MSG_MAIN_MENU_10
#Exit gpSP
!Sair do EMULADOR

# MSG_MAIN_MENU_11
#Languages and other options
!Línguas e outras opções

# MSG_MAIN_MENU_HELP_0
#Select to set display parameters and frameskip behavior,\n
#audio on/off, audio buffer size, and audio filtering.
!\n\n
!Selecione para definir as configurcoes de tela e audio.\n
!Tela: Modos de exibicao, filtragem e configuracao do salto de quadro.\n
!Audio: ligar ou desligar, e configurar o tamanho da memoria temporaria.

# MSG_MAIN_MENU_HELP_1
#Select to load the game state from the current slot for this game,\n
#if it exists (see the extended menu for more information)\n
#Press left + right to change the current slot.
!\n\n
!Selecione para carregar o ponto salvo deste jogo, na atual entrada,\n
!caso nao exista (veja o menu completo para mais informacoes)\n
!Pressione esquerda ou direita para alterar o numero da entrada.

# MSG_MAIN_MENU_HELP_2
#Select to save the game state to the current slot for this game.\n
#See the extended menu for more information.\n
#Press left + right to change the current slot.
!\n\n
!Selecione para salvar o jogo na atual entrada, exatamente neste ponto.\n
!Veja o menu completo para mais informacoes.\n
!Pressione esquerda ou direita para alterar o numero da entrada.

# MSG_MAIN_MENU_HELP_3
#Select to enter a menu for loading, saving, and viewing the\n
#currently active savestate for this game (or to load a savestate\n
#file from another game)
!\n\n
!Selecione este menu para carregar, salvar ou exibir o atual\n
!arquivo salvo para este jogo (ou carregar um arquivo salvo\n
!de outro jogo)

# MSG_MAIN_MENU_HELP_4
#Select to change the in-game behavior of the PSP buttons and d-pad.
!\n\n\n\n
!Selecione para editar a configuracao dos botoes do controlador.

# MSG_MAIN_MENU_HELP_5
#Select to change the in-game behavior of the PSP analog nub.
!\n\n\n\n
!Selecione para editar a configuracao dos botoes do controlador analógico.

# MSG_MAIN_MENU_HELP_6
#Select to manage cheats.
!\n\n\n\n
!Selecione para gerenciar cheats.

# MSG_MAIN_MENU_HELP_7
#Select to load a new game (will exit a game if currently playing).
!\n\n\n
!Selecione para carregar outro jogo\n
!(vai encerrar o atual jogo que voce esta jogando)

# MSG_MAIN_MENU_HELP_8
#Select to reset the GBA with the current game loaded.
!\n\n\n\n
!Selecione para reiniciar seu atual jogo.

# MSG_MAIN_MENU_HELP_9
#Select to exit this menu and resume gameplay.
!\n\n\n\n
!Selecione para sair deste menu e voltar ao jogo.

# MSG_MAIN_MENU_HELP_10
#Select to exit gpSP and return to the PSP XMB/loader.
!\n\n\n\n
!Selecione para sair do EMULADOR e voltar para o Navegador.

# MSG_MAIN_MENU_HELP_11
#Languages, set backup behavior, and set device clock speed.
!\n\n\n
!Languages, definir o comportamento do backup e definir\n
!a velocidade do relogio do dispositivo.

# MSG_SCALE
#Display scaling: %s
!Exibição de escala  $$$: %s

# MSG_FILTER
#Screen filtering: %s
!Filtragem de tela   $$: %s

# MSG_RATIO
#TV output ratio: %s
!Tipo de tela da TV   $: %s

# MSG_INTERLACE
#TV output interlace: %s
!Modo de video da TV : %s

# MSG_SKIP_TYPE
#Frameskip type: %s
!Tipo frameskip     $$: %s

# MSG_SKIP_VALUE
#Frameskip value: %d
!Valor skip quadro $$$: %d

# MSG_SKIP_RANDOM
#Framskip variation: %s
!Variação Framskip : %s

# MSG_AUDIO_ENABLE
#Audio output: %s
!Saida de audio   : %s

# MSG_AUDIO_BUFFER
#Audio buffer: %s
!Buffer de áudio : %s

# MSG_SCREEN_SHOT
#Screen shot
!Captura de tela

# MSG_DISPLAY_SCALE
#Scale: %d
!Scale : %d

# MSG_MENU_RETURN_MAIN
#Back
!Voltar

# MSG_G_S_MENU_HELP_0
#Determines how the GBA screen is resized in relation to the entire\n
#screen. Select unscaled 3:2 for GBA resolution, scaled 3:2 for GBA\n
#aspect ratio scaled to fill the height of the PSP screen, and\n
#fullscreen to fill the entire PSP screen.
!\n
!Determina como a tela do EMULADOR eh redimensionada em relacao a tela\n
!da TV. Selecione o tipo de proporcao 4:3 para a resolucao do EMULADOR.\n
!selecionada a proporcao 4:3, o EMULADOR e dimensionado para preencher\n
!a altura da tela da TV, e 16:9 (fullscreen) para preenche-la totalmente.

# MSG_G_S_MENU_HELP_1
#Determines whether or not bilinear filtering should be used when\n
#scaling the screen. Selecting this will produce a more even and\n
#smooth image, at the cost of being blurry and having less vibrant colors.
!\n\n
!Determina se vai usar ou nao a filtragem bilinear para proporcao\n
!de tela escolhida. Selecionando isto produzira uma imagem mais\n
!uniforme e suave, ao custo de ser borrada e com cores menos vibrantes.

# MSG_G_S_MENU_HELP_2
#Determines what kind of frameskipping should be employed.\n
#Frameskipping may improve emulation speed of many games.\n
#Off: Do not skip any frames.\n
#Auto: Skip up to N frames (see next option) as needed.\n
#Manual: Always render only 1 out of N + 1 frames.
!\n
!Determina que tipo de salto de quadro deve ser empregada.\n
!Salto de quadro pode melhorar a velocidade de emulacao de muitos jogos.\n
!Desligar: Nao salta nenhum quadro.\n
!Automatico: Salta ate N quadros (veja proxima opcao), conforme necessario.\n
!Manual: Sempre renderizar apenas 1 de N + 1 quadros.

# MSG_G_S_MENU_HELP_3
#For auto frameskip, determines the maximum number of frames that\n
#are allowed to be skipped consecutively.\n
#For manual frameskip, determines the number of frames that will\n
#always be skipped.
!\n
!Para auto salto de quadro, determina o numero maximo de quadros\n
!saltados consecutivamente.\n
!Para salto de quadro manual, determina o numero de quadros que\n
!serao sempre saltados.

# MSG_G_S_MENU_HELP_4
#If objects in the game flicker at a regular rate certain manual\n
#frameskip values may cause them to normally disappear. Change this\n
#value to 'random' to avoid this. Do not use otherwise, as it tends to\n
#make the image quality worse, especially in high motion games.
!\n
!Se objetos tremem no jogo em um ritmo regular, certos valores de saltos\n
!de quadros manuais podem os fazer normalmente desaparecer. Mude este\n
!valor para "aleatorio" para evitar isso. Nao use o contrario, pois ele tende\n
!a piorar a qualidade da imagem, especialmente em jogos de alto movimento.

# MSG_G_S_MENU_HELP_5
#Select 'no' to turn off all audio output. This will not result in a\n
#significant change in performance.
!\n\n\n
!Escolha "desativada" para desligar toda a saida de audio.\n
!Isto nao vai resultar em uma melhora significativa no desempenho.

# MSG_G_S_MENU_HELP_6
#Set the size (in bytes) of the audio buffer. Larger values may result\n
#in slightly better performance at the cost of latency; the lowest\n
#value will give the most responsive audio.\n
#This option requires gpSP to be restarted before it will take effect.
!\n
!Defina o tamanho (em bytes) da Memoria temporaria do audio.\n
!Valores maiores podem resultar em um desempenho\n
!ligeiramente melhor as custas de latencia.\n
!O valor mais baixo vai dar um audio mais responsivo.\n
!Esta opcao requer que o EMULADOR seja reiniciado para que ela tenha efeito.

# MSG_G_S_MENU_HELP_7
#Screen shot
!\n\n\n\n
!Captura a imagem da tela do atual jogo.

# MSG_G_S_MENU_HELP_8
#Return to the main menu.
!\n\n\n\n
!Retornar ao menu principal.

# MSG_G_S_MENU_HELP_9
#TV output ratio
!\n\n\n\n
!Escolha o tipo de tela da sua TV.

# MSG_G_S_MENU_HELP_10
#Scaling
!\n\n\n\n
!Scaling

# MSG_G_S_MENU_HELP_11
#TV output interlace
!\n\n\n\n
!Escolha que modo de resolucao sua TV consegui reproduzir, normal NTSC.

# MSG_STATE_MENU_DATE_FMT_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%04d/%02d/%02d  %-10s  %02d:%02d:%02d          
!%04d/%02d/%02d  %-10s  %02d:%02d:%02d          

# MSG_STATE_MENU_DATE_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%02d/%02d/%04d  %-10s  %02d:%02d:%02d          
!%02d/%02d/%04d  %-10s  %02d:%02d:%02d          

# MSG_STATE_MENU_DATE_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%02d.%02d.%04d  %-10s  %02d:%02d:%02d          
!%02d.%02d.%04d  %-10s  %02d:%02d:%02d          

# MSG_STATE_MENU_DATE_NONE_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#----/--/--  ----------  --:--:--          
!----/--/--  ----------  --:--:--          

# MSG_STATE_MENU_DATE_NONE_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#--/--/----  ----------  --:--:--          
!--/--/----  ----------  --:--:--          

# MSG_STATE_MENU_DATE_NONE_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#--.--.----  ----------  --:--:--          
!--.--.----  ----------  --:--:--          

# MSG_STATE_MENU_STATE_NONE
#No savestate exists for this slot
!\n   $Nenhum arquivo salvo nesta entrada

# MSG_STATE_MENU_TITLE
#Savestate options:
!Opcoes de arquivos salvos:

# MSG_STATE_MENU_0
#Load savestate from current slot
!Carregar de dados

# MSG_STATE_MENU_1
#Save savestate to current slot
!Salvar de dados

# MSG_STATE_MENU_2
#Load savestate from file
!Carregar de arquivo

# MSG_STATE_MENU_3
#Current savestate slot: %d
!Ranhura atual : %d

# MSG_STATE_MENU_4
#Back
!Voltar

# MSG_STATE_MENU_HELP_0
#Select to load the game state from the current slot for this game.\n
#Press left + right to change the current slot.
!Vai carregar o ponto salvo na atual entrada para jogo que esta rodando.\n
!Exemplo: Se tiver selecionado a entrada 1, quando carregar o arquivo,\n
!verifique se eh o arquivo certo do seu jogo, para evitar carregar um\n
!arquivo de outro jogo.\n
!Pressione esquerda ou direita para alterar o numero da entrada.

# MSG_STATE_MENU_HELP_1
#Select to save the game state to the current slot for this game.\n
#Press left + right to change the current slot.
!Selecione para salvar o jogo que esta rodando, na atual entrada.\n
!Exemplo: Se tiver selecionado a entrada 1, quando salvar o arquivo,\n
!verifique se eh a entrada correta que salvou seu jogo pelo ultima vez,\n
!para evitar salvar seu atual jogo em cima de um arquivo de outro jogo.\n
!Pressione esquerda ou direita para alterar o numero da entrada.

# MSG_STATE_MENU_HELP_2
#Restore gameplay from a savestate file.\n
#Note: The same file used to save the state must be present.
!\n\n\n
!Restaurar jogo atraves de um arquivo salvo.\n
!Nota: Deve ser usado o mesmo arquivo salvo anteriormente.

# MSG_STATE_MENU_HELP_3
#Change the current savestate slot.
!\n\n\n\n
!Selecione ou mude a entrada atual para salvamentos.

# MSG_STATE_MENU_HELP_4
#Return to the main menu.
!\n\n\n\n
!Retornar ao menu principal.

# MSG_PAD_MENU_0
#D-pad up: %s
!D-pad cima       $: %s

# MSG_PAD_MENU_1
#D-pad down: %s
!D-pad baixo      $$: %s

# MSG_PAD_MENU_2
#D-pad left: %s
!D-pad esquerda : %s

# MSG_PAD_MENU_3
#D-pad right: %s
!D-pad direita    $: %s

# MSG_PAD_MENU_4
#Cross: %s
!Cruz               $$$: %s

# MSG_PAD_MENU_5
#Circle: %s
!Circulo            $: %s

# MSG_PAD_MENU_6
#Square: %s
!Quadrado         $$$: %s

# MSG_PAD_MENU_7
#Triangle: %s
!Triangulo        $$$: %s

# MSG_PAD_MENU_8
#Left Trigger: %s
!L-Trigger         $$: %s

# MSG_PAD_MENU_9
#Right Trigger: %s
!R-Trigger         $$: %s

# MSG_PAD_MENU_10
#Start: %s
!Start              $$$: %s

# MSG_PAD_MENU_11
#Select: %s
!Select             $$$: %s

# MSG_PAD_MENU_12
#Use default map: %s
!Padrao de layout : %s

# MSG_PAD_MENU_13
#Back
!Voltar

# MSG_PAD_MENU_HELP_12
#Use default map
!\n\n\n\n
!Retorna a configuracao padrao do controlador.

# MSG_PAD_MENU_HELP_13
#Return to the main menu.
!\n\n\n\n
!Retornar ao menu principal.

#Settings configuration PAD

# MSG_PAD_MENU_CFG_0
#UP
!CIMA

# MSG_PAD_MENU_CFG_1
#DOWN
!BAIXO

# MSG_PAD_MENU_CFG_2
#LEFT
!ESQUERDA

# MSG_PAD_MENU_CFG_3
#RIGHT
!DIREITA

# MSG_PAD_MENU_CFG_4
#A
!A

# MSG_PAD_MENU_CFG_5
#B
!B

# MSG_PAD_MENU_CFG_6
#L
!L

# MSG_PAD_MENU_CFG_7
#R
!R

# MSG_PAD_MENU_CFG_8
#START
!START

# MSG_PAD_MENU_CFG_9
#SELECT
!SELECT

# MSG_PAD_MENU_CFG_10
#MENU
!MENU

# MSG_PAD_MENU_CFG_11
#FASTFORWARD
!AVANCO RAPIDO

# MSG_PAD_MENU_CFG_12
#LOAD STATE
!CARREGAR PONTO SALVO

# MSG_PAD_MENU_CFG_13
#SAVE STATE
!SALVAR JOGO NESTE PONTO

# MSG_PAD_MENU_CFG_14
#RAPIDFIRE A
!FOGO RAPIDO A

# MSG_PAD_MENU_CFG_15
#RAPIDFIRE B
!FOGO RAPIDO B

# MSG_PAD_MENU_CFG_16
#RAPIDFIRE L
!FOGO RAPIDO L

# MSG_PAD_MENU_CFG_17
#RAPIDFIRE R
!FOGO RAPIDO R

# MSG_PAD_MENU_CFG_18
#VOLUME UP
!AUMENTAR VOLUME

# MSG_PAD_MENU_CFG_19
#VOLUME DOWN
!DIMINUIR VOLUME

# MSG_PAD_MENU_CFG_20
#DISPLAY FPS
!EXIBIR FPS NA TELA

# MSG_PAD_MENU_CFG_21
#NOTHING
!NADA

# MSG_PAD_MENU_CFG_HELP_0
#Up button on GBA d-pad.
!\n\n\n\n
!Botao CIMA do controlador.

# MSG_PAD_MENU_CFG_HELP_1
#Down button on GBA d-pad.
!\n\n\n\n
!Botao BAIXO do controlador.

# MSG_PAD_MENU_CFG_HELP_2
#Left button on GBA d-pad.
!\n\n\n\n
!Botao ESQUERDA do controlador.

# MSG_PAD_MENU_CFG_HELP_3
#Right button on GBA d-pad.
!\n\n\n\n
!Botao DIREITA do controlador.

# MSG_PAD_MENU_CFG_HELP_4
#A button on GBA.
!\n\n\n\n
!Botao A.

# MSG_PAD_MENU_CFG_HELP_5
#B button on GBA.
!\n\n\n\n
!Botao B.

# MSG_PAD_MENU_CFG_HELP_6
#Left shoulder button on GBA.
!\n\n\n\n
!Botao de cima ESQUERDO.

# MSG_PAD_MENU_CFG_HELP_7
#Right shoulder button on GBA.
!\n\n\n\n
!Botao de cima DIREITO.

# MSG_PAD_MENU_CFG_HELP_8
#Start button on GBA.
!\n\n\n\n
!Botao START.

# MSG_PAD_MENU_CFG_HELP_9
#Select button on GBA.
!\n\n\n\n
!Botao SELECT.

# MSG_PAD_MENU_CFG_HELP_10
#Brings up the options menu.
!\n\n\n\n
!Abre o menu de opcoes.

# MSG_PAD_MENU_CFG_HELP_11
#Toggles fastforward on/off (don't expect it to do much or anything)
!\n\n\n\n
!Altera avanco rapido para ligar/desligar (nao espere que ele faca muita coisa)

# MSG_PAD_MENU_CFG_HELP_12
#Loads the game state from the current slot.
!\n\n\n\n
!Carrega o ponto salvo do jogo que esta rodando.

# MSG_PAD_MENU_CFG_HELP_13
#Saves the game state to the current slot.
!\n\n\n\n
!Salva o jogo que esta rodando exatamente neste ponto.

# MSG_PAD_MENU_CFG_HELP_14
#Rapidly press/release the A button on GBA.
!\n\n\n\n
!Pressione/solte com rapidez no botao A.

# MSG_PAD_MENU_CFG_HELP_15
#Rapidly press/release the B button on GBA.
!\n\n\n\n
!Pressione/solte com rapidez no botao B.

# MSG_PAD_MENU_CFG_HELP_16
#Rapidly press/release the L shoulder button on GBA.
!\n\n\n\n
!Pressione/solte com rapidez no botao de cima L.

# MSG_PAD_MENU_CFG_HELP_17
#Rapidly press/release the R shoulder button on GBA.
!\n\n\n\n
!Pressione/solte com rapidez no botao de cima R.

# MSG_PAD_MENU_CFG_HELP_18
#Increases the volume.
!\n\n\n\n
!Aumenta o volume.

# MSG_PAD_MENU_CFG_HELP_19
#Decreases the volume.
!\n\n\n\n
!Diminui o volume.

# MSG_PAD_MENU_CFG_HELP_20
#Displays virtual/drawn frames per second.
!\n\n\n\n
!Mostra Eficacia/Distorcao dos quadros por segundo na tela.

# MSG_PAD_MENU_CFG_HELP_21
#Does nothing.
!\n\n\n\n
!Nao faz nada.

# MSG_A_PAD_MENU_0
#Analog up: %s
!Analógico para cima       $: %s

# MSG_A_PAD_MENU_1
#Analog down: %s
!Analógico para baixo      $$: %s

# MSG_A_PAD_MENU_2
#Analog left: %s
!Analógico para esquerda : %s

# MSG_A_PAD_MENU_3
#Analog right: %s
!Analógico para direita    $: %s

# MSG_A_PAD_MENU_4
#Enable analog: %s
!Habilitar analógico           : %s

# MSG_A_PAD_MENU_5
#Analog sensitivity: %d
!Sensibilidade do analógico : %d

# MSG_A_PAD_MENU_6
#Tilt sensor : %s
!Sensor de inclinação        : %s

# MSG_A_PAD_MENU_7
#Back
!Voltar

# MSG_A_PAD_MENU_HELP_0
#Select 'no' to block analog input entirely.
!\n\n\n\n
!Selecione "nao" para bloquear a entrada analogica.

# MSG_A_PAD_MENU_HELP_1
#Determine sensitivity/responsiveness of the analog input.\n
#Lower numbers are less sensitive.
!\n\n\n
!Determinar a sensibilidade/resposta da entrada analogica.\n
!Os numeros mais baixos sao menos sensiveis.

# MSG_A_PAD_MENU_HELP_2
#Tilt sensor
!\n\n\n\n
!Sensor de inclinação

# MSG_A_PAD_MENU_HELP_3
#Return to the main menu.
!\n\n\n\n
!Retornar ao menu principal.

# MSG_CHEAT_MENU_NON_LOAD
#cheat %d (none loaded)
!cheat %d (nada carregado)

# MSG_CHEAT_MENU_0
#cheat %d (%s): %%s
!cheat %d (%s): %%s

# MSG_CHEAT_MENU_1
#Load Cheat File
!Carregar arquivo Cheat

# MSG_CHEAT_MENU_2
#Clock speed: %s
!Velocidade do relógio $$: %s

# MSG_CHEAT_MENU_3
#Update backup: %s
!Salvar atualização    : %s

# MSG_CHEAT_MENU_4
#Back
!Voltar

# MSG_CHEAT_MENU_HELP_0
#Activate/deactivate this cheat code.
!\n\n\n\n
!Ativar/desativar codigo cheat.

# MSG_CHEAT_MENU_HELP_1
# Load Cheat File
!\n\n\n\n
!Procure e carregue um arquivo Cheat.

# MSG_CHEAT_MENU_HELP_2
#Change the clock speed of the device. Higher clock speed will yield\n
#better performance, but will use drain battery life further.
!\n\n\n
!Mude a velocidade do relogio. Maior velocidade do relogio ira produzir\n
!um melhor desempenho, mas vai aumentar o consumo da carga da bateria.

# MSG_CHEAT_MENU_HELP_3
#Determines when in-game save files should be written back to\n
#memstick. If set to 'automatic' writebacks will occur shortly after\n
#the game's backup is altered. On 'exit only' it will only be written\n
#back when you exit from this menu (NOT from using the home button).\n
#Use the latter with extreme care.
!\n
!Determina quando em-jogo os arquivos de salvamento devem ser gravados\n
!de volta para memstick. Se definido como "automatico" as escritas de\n
!volta vao ocorrer logo apos o backup do jogo e alterada. Em "Ao sair"\n
!ela so vai ser escrito de volta quando voce sair deste menu (NAO use o \n
!botao home). Utilize este ultimo com muito cuidado.

# MSG_CHEAT_MENU_HELP_4
#Return to the main menu.
!\n\n\n\n
!Retornar ao menu principal.

# MSG_MISC_MENU_0
#Emulate Core : %s
!Emulate Core : %s

# MSG_MISC_MENU_1
#Debug mode : %s
!Debug mode : %s

# MSG_MISC_MENU_2
#Language : %s
!Língua : %s

# MSG_MISC_MENU_3
#Fake Fat : %s
!Falsificação Fat       $$$: %s

# MSG_MISC_MENU_4
#Boot Mode : %s
!Modo de inicialização : %s

# MSG_MISC_MENU_5
#Brightness : %d
!Brilho : %d

# MSG_MISC_MENU_HELP_0
#Emulate Core
!\n\n\n\n
!Emulate Core

# MSG_MISC_MENU_HELP_1
#Debug mode
!\n\n\n\n
!Debug mode

# MSG_MISC_MENU_HELP_2
#Language
!\n\n\n\n
!Língua

# MSG_MISC_MENU_HELP_3
#Fake Fat
!\n\n\n\n
!Falsificação Fat

# MSG_MISC_MENU_HELP_4
#Boot Mode
!\n\n\n\n
!Modo de inicialização

# MSG_MISC_MENU_HELP_5
#Brightness
!\n\n\n\n
!Brilho

# MSG_NON_LOAD_GAME
#No game loaded yet
!             $$Nenhum jogo carregado

# MSG_WDAY_0
#Sunday
!Domingo

# MSG_WDAY_1
#Monday
!Segunda

# MSG_WDAY_2
#Tuesday
!Terca

# MSG_WDAY_3
#Wednesday
!Quarta

# MSG_WDAY_4
#Thursday
!Quinta

# MSG_WDAY_5
#Friday
!Sexta

# MSG_WDAY_6
#Saturday
!Sabado

# MSG_YES
#yes
!ativada

# MSG_NO
#no
!desativada

# MSG_YES_NO
#Yes - X / No - O
!Yes - X / No - O

# MSG_ENABLED
#enabled
!habilitar

# MSG_DISABLED
#disabled
!desabilitar

# MSG_SCALE_UNSCALED
#unscaled 3:2
!sem modificacoes

# MSG_SCALE_SCALED
#scaled 3:2
!escamado 3:2

# MSG_SCALE_FULL
#fullscreen 16:9
!tela cheia 16:9

# MSG_SCN_OPT1
#option 1
!opção 1

# MSG_SCN_OPT2
#option 2
!opção 2

# MSG_FS_AUTO
#automatic
!automático

# MSG_FS_MANUAL
#manual
!manual

# MSG_FS_OFF
#off
!desligar

# MSG_FS_UNIFORM
#uniform
!uniforme

# MSG_FS_RAMDOM
#random
!aleatória

# MSG_SB_2048
#2048 bytes
!2048 bytes

# MSG_SB_3072
#3072 bytes
!3072 bytes

# MSG_SB_4096
#4096 bytes
!4096 bytes

# MSG_SB_5120
#5120 bytes
!5120 bytes

# MSG_SB_6144
#6144 bytes
!6144 bytes

# MSG_SB_7168
#7168 bytes
!7168 bytes

# MSG_SB_8192
#8192 bytes
!8192 bytes

# MSG_SB_9216
#9216 bytes
!9216 bytes

# MSG_SB_10240
#10240 bytes
!10240 bytes

# MSG_SB_11264
#11264 bytes
!11264 bytes

# MSG_SB_12288
#12288 bytes
!12288 bytes

# MSG_BK_EXITONLY
#exit only
!ao sair

# MSG_BK_AUTO
#automatic
!automático

# MSG_CLK_33
#33MHz
!33MHz

# MSG_CLK_66
#66MHz
!66MHz

# MSG_CLK_100
#100MHz
!100MHz

# MSG_CLK_133
#133MHz
!133MHz

# MSG_CLK_166
#166MHz
!166MHz

# MSG_CLK_200
#200MHz
!200MHz

# MSG_CLK_233
#233MHz
!233MHz

# MSG_CLK_266
#266MHz
!266MHz

# MSG_CLK_300
#300MHz
!300MHz

# MSG_CLK_333
#333MHz
!333MHz

# MSG_SS_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%04d_%02d_%02d_%s%02d_%02d_%02d_%03d
!%04d_%02d_%02d_%s%02d_%02d_%02d_%03d

# MSG_SS_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%s%02d_%02d_%04d_%02d_%02d_%02d_%03d
!%s%02d_%02d_%04d_%02d_%02d_%02d_%03d

# MSG_SS_FMT_3
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%s%02d_%02d_%04d_%02d_%02d_%02d_%03d
!%s%02d_%02d_%04d_%02d_%02d_%02d_%03d

# MSG_ERR_BIOS_1
#Sorry, but gpSP requires a Gameboy Advance BIOS image to run\n
#correctly. Make sure to get an authentic one (search the web,\n
#beg other people if you want, but don't hold me accountable\n
#if you get hated or banned for it), it'll be exactly 16384\n
#bytes large and should have the following md5sum value:\n\n
!Desculpe, mas gpS2-kai requer uma imagem BIOS do Gameboy Advance\n
!para funcionar corretamente. Certifique-se de obter uma autentica\n
!(pesquisar na web, se voce quiser, pedir as outras pessoas, mas\n
!nao me responsabilizo se voce for banido por isso), vai ser\n
!exatamente 16.384 bytes de tamanho e deve ter o seguinte valor md5sum:\n\n

# MSG_ERR_BIOS_2
#a860e8c0b6d573d191e4ec7db1b1e4f6 or 1c0d67db9e1208b95a1506b1688a0ad6\n\n
#Other BIOS files might work either partially completely, I\n
#really don't know.\n\n
#When you do get it name it gba_bios.bin and put it in the\n
#same directory as this EBOOT.\n\n
#Good luck. Press any button to exit.\n
!a860e8c0b6d573d191e4ec7db1b1e4f6 or 1c0d67db9e1208b95a1506b1688a0ad6\n\n
!Outros arquivos de BIOS podem funcionar parcial ou completamente, eu\n
!realmente nao sei.\n\n
!Quando voce fizer isso nomea-lo para gba_bios.bin e coloca-lo no mesmo\n
!diretorio que esta EBOOT.\n\n
!Boa sorte. Pressione qualquer tecla para sair.\n

# MSG_ERR_BIOS_MD5
#This BIOS is not regular.\n
#There is a possibility of various trouble.\n\n
#Please use regular BIOS.\n
!Esta BIOS nao e valida.\n
!Existe uma possibilidade de muitos problemas.\n\n
!Por favor use uma BIOS valida.\n

# MSG_R_4_3
#ratio 4:3
!Normal 4:3

# MSG_R_16_9
#ratio 16:9
!Retangular 16:9

# MSG_I_NON
#progressive
!progressivo

# MSG_I_ON
#interlace
!entrelacado

# MSG_INIT_END
#Initialization end
!Fim da inicializacao

# MSG_LOAD_STATE
#Load State.
!Carregar Estado.

# MSG_LOAD_STATE_END
#Load State End.
!Fim do Carregamento do Estado.

# MSG_SAVE_STATE
#Save State.
!Salvar Estado.

# MSG_SAVE_STATE_END
#Save State End.
!Fim do Salvamento do Estado.

# MSG_LOAD_STATE_No
#Load State No: %d
!Load State No: %d

# MSG_SAVE_STATE_No
#Save State No: %d
!Save State No: %d

# MSG_LOAD_ZIP_ROM
#Load ZIP ROM.
!Load ZIP ROM.

# MSG_LOAD_ROM
#Load ROM.
!Load ROM.

# MSG_LOAD_ROM_OK
#Load ROM OK.
!Load ROM OK.

# MSG_CHEAT_MENU_5
#Cheat page: %d
!Pagina do cheat : %d

# MSG_CHEAT_MENU_HELP_5
#Cheat page
!\n\n\n\n
!Navegue entre as paginas e se quiser ative um cheat.

# MSG_CHEAT_MENU_6
#Enable HOME: %s
!Habilitar "HOME"        $$: %s

# MSG_CHEAT_MENU_HELP_6
#Enable HOME
!\n\n\n\n
!Habilitar PAGINA PRINCIPAL
