# messege file
# Русский перевод by ErikPshat ©

#To align text, use the following information: symbol "space" = 4 pixels; symbol "$" = 1 pixel.

# MSG_RETURN_MENU
#Press O to return to the main menu.
!Нажмите О для перехода в Главное меню.

# MSG_MENU_DATE
#TIME 
!

# MSG_MENU_BATTERY
#battery LifePercent:%3d%% LifeTime:%3d min.
!Батарея: %3d%% Осталось:%3d min.

# MSG_DATE_FMT_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%04d/%02d/%02d  %-10s  %02d:%02d:%02d          
!%04d/%02d/%02d  %-10s  %02d:%02d:%02d          

# MSG_DATE_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%02d/%02d/%04d  %-10s  %02d:%02d:%02d          
!%02d/%02d/%04d  %-10s  %02d:%02d:%02d          

# MSG_DATE_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%02d.%02d.%04d  %-10s  %02d:%02d:%02d          
!%02d.%02d.%04d  %-10s  %02d:%02d:%02d          

# MSG_MAIN_MENU_0
#Graphics and Sound options
!Опции графики и звука

# MSG_MAIN_MENU_1
#Load state from slot: %d
!Загрузить из слота : %d

# MSG_MAIN_MENU_2
#Save state to slot: %d
!Сохранить в слот    : %d

# MSG_MAIN_MENU_3
#Savestate options
!Настройки сохранений

# MSG_MAIN_MENU_4
#Configure gamepad input
!Настройки управления

# MSG_MAIN_MENU_5
#Configure analog input
!Настройки джойстика

# MSG_MAIN_MENU_6
#Cheats Manager
!Менеджер читов

# MSG_MAIN_MENU_7
#Load new game
!Загрузить новую игру

# MSG_MAIN_MENU_8
#Restart game
!Перезагрузить игру

# MSG_MAIN_MENU_9
#Return to game
!Продолжить игру

# MSG_MAIN_MENU_10
#Exit gpSP
!Выход в XMB

# MSG_MAIN_MENU_11
#Language and other options
!Языки и прочие опции

# MSG_MAIN_MENU_HELP_0
#Select to set display parameters and frameskip behavior,\n
#audio on/off, audio buffer size, and audio filtering.
!\n\n\n\n
!Настройки экрана, пропуска кадров, звука, аудиобуфера и фильтрации.

# MSG_MAIN_MENU_HELP_1
#Select to load the game state from the current slot for this game,\n
#if it exists (see the extended menu for more information)\n
#Press left + right to change the current slot.
!\n\n
!Загрузка сохранённой игры из текущего слота\n
!(при наличии отображается в меню справа).\n
!Влево/вправо - смена слота.

# MSG_MAIN_MENU_HELP_2
#Select to save the game state to the current slot for this game.\n
#See the extended menu for more information.\n
#Press left + right to change the current slot.
!\n\n
!Сохранение игрового состояния в выбраный слот\n
!(в меню справа - текущее состояние слота).\n
!Влево/вправо - смена слота.

# MSG_MAIN_MENU_HELP_3
#Select to enter a menu for loading, saving, and viewing the\n
#currently active savestate for this game (or to load a savestate\n
#file from another game)
!\n\n
!Менеджер сохранений с возможностью просмотра\n
!данных и импорта данных из внешнего файла\n
!(даже от другой игры).

# MSG_MAIN_MENU_HELP_4
#Select to change the in-game behavior of the PSP buttons and d-pad.
!\n\n\n\n
!Настройки ассоциации кнопок GBA - PSP.

# MSG_MAIN_MENU_HELP_5
#Select to change the in-game behavior of the PSP analog nub.
!\n\n\n\n
!Настройки управления аналоговым джойстиком.

# MSG_MAIN_MENU_HELP_6
#Select to manage cheats.
!\n\n\n
!Менеджер читов.

# MSG_MAIN_MENU_HELP_7
#Select to load a new game (will exit a game if currently playing).
!\n\n\n\n
!Выбор новой игры (текущая будет прервана).

# MSG_MAIN_MENU_HELP_8
#Select to reset the GBA with the current game loaded.
!\n\n\n\n
!Перезагрузка эмуляции текущего рома GBA.

# MSG_MAIN_MENU_HELP_9
#Select to exit this menu and resume gameplay.
!\n\n\n\n
!Выход из меню и возврат к игре.

# MSG_MAIN_MENU_HELP_10
#Select to exit gpSP and return to the PSP XMB/loader.
!\n\n\n\n
!Выход из gpSP в меню PSP.

# MSG_MAIN_MENU_HELP_11
#Languages, set backup behavior, and set device clock speed.
!\n\n\n\n
!Язык меню, настройка частоты процессора и прочие опции.

# MSG_SCALE
#Display scaling    : %s
!Вывод графики          $: %s

# MSG_FILTER
#Screen filtering  : %s
!Фильтрация              $$$: %s

# MSG_RATIO
#TV output ratio    : %s
!Аспект ТВ-выхода     $$$: %s

# MSG_INTERLACE
#TV output interlace : %s
!Развёртка ТВ-выхода : %s

# MSG_SKIP_TYPE
#Frameskip type    : %s
!Пропуск кадров    : %s

# MSG_SKIP_VALUE
#Frameskip value   : %d
!Частота пропуска : %d

# MSG_SKIP_RANDOM
#Framskip variation: %s
!Тип пропуска      $$: %s

# MSG_AUDIO_ENABLE
#Audio output: %s
!Аудио вывод : %s

# MSG_AUDIO_BUFFER
#Audio buffer: %s
!Аудио буфер : %s

# MSG_SCREEN_SHOT
#Screen shot
!Сделать скриншот

# MSG_DISPLAY_SCALE
#Scale : %d
!Масштаб : %d

# MSG_MENU_RETURN_MAIN
#Back
!Назад

# MSG_G_S_MENU_HELP_0
#Determines how the GBA screen is resized in relation to the entire\n
#screen. Select unscaled 3:2 for GBA resolution, scaled 3:2 for GBA\n
#aspect ratio scaled to fill the height of the PSP screen, and\n
#fullscreen to fill the entire PSP screen.
!\n
!Настройка растягиваня картинки GBA под экран PSP.\n
!unscaled 3:2 - оригинальное разрешения GBA,\n
!scaled 3:2     - растягивание с сохранением пропорций,\n
!fullscreen    - полноэкранное изображение.

# MSG_G_S_MENU_HELP_1
#Determines whether or not bilinear filtering should be used when\n
#scaling the screen. Selecting this will produce a more even and\n
#smooth image, at the cost of being blurry and having less vibrant\n
#colors.
!\n\n
!Билинейная фильтрация при растягивании изображения под экран PSP.\n
!Картинка будет несколько размыта, с более плавным переходом\n
!цветов на границе пикселей.

# MSG_G_S_MENU_HELP_2
#Determines what kind of frameskipping should be employed.\n
#Frameskipping may improve emulation speed of many games.\n
#Off: Do not skip any frames.\n
#Auto: Skip up to N frames (see next option) as needed.\n
#Manual: Always render only 1 out of N + 1 frames.
!\n
!Настройка пропуска кадров при эмуляции.\n
!Данная опция иногда позволяет увеличить скорость.\n
!Откл: Не пропускать кадры.\n
!Авто: Пропуск N кадров (след. опция), если нужно.\n
!Точно: Рендер только одного из N + 1 кадров.

# MSG_G_S_MENU_HELP_3
#For auto frameskip, determines the maximum number of frames that\n
#are allowed to be skipped consecutively.\n
#For manual frameskip, determines the number of frames that will\n
#always be skipped.
!\n
!Устанавливает максимальное количество кадров,\n
!которые могут быть пропущены при значении "Авто".\n
!Устанавливает количество кадров, пропускаемых\n
!при значении "Точно".

# MSG_G_S_MENU_HELP_4
#If objects in the game flicker at a regular rate certain manual\n
#frameskip values may cause them to normally disappear. Change this\n
#value to 'random' to avoid this. Do not use otherwise, as it tends to\n
#make the image quality worse, especially in high motion games.
!\n\n\n\n
!Алгоритм процедуры пропуска кадров.\n

# MSG_G_S_MENU_HELP_5
#Select 'no' to turn off all audio output. This will not result in a\n
#significant change in performance.
!\n\n\n
!Выберите "нет" для отключения обработки звука.\n
!Не всегда влияет на скорость эмуляции.

# MSG_G_S_MENU_HELP_6
#Set the size (in bytes) of the audio buffer. Larger values may result\n
#in slightly better performance at the cost of latency; the lowest\n
#value will give the most responsive audio.\n
#This option requires gpSP to be restarted before it will take effect.
!\n\n
!Размер аудиобуфера (в байтах).\n
!Качество звука пропорционально выбраному значению.\n
!Изменения вступят в силу, после перезапуска эмулятора.

# MSG_G_S_MENU_HELP_7
#Screen shot
!\n\n\n\n
!Сохранить снимок экрана

# MSG_G_S_MENU_HELP_8
#Return to the main menu.
!\n\n\n\n
!Возврат в главное меню.

# MSG_G_S_MENU_HELP_9
#TV output ratio
!\n\n\n\n
!Пропорции картинки, выводимой на экран ТВ

# MSG_G_S_MENU_HELP_10
#Scaling
!\n\n\n\n
!Масштабирование изображения

# MSG_G_S_MENU_HELP_11
#TV output interlace
!\n\n\n\n
!Интерлейсинг при выводе на экран ТВ

# MSG_STATE_MENU_DATE_FMT_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%04d/%02d/%02d  %-10s  %02d:%02d:%02d          
!%04d/%02d/%02d  %-10s  %02d:%02d:%02d          

# MSG_STATE_MENU_DATE_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%02d/%02d/%04d  %-10s  %02d:%02d:%02d          
!%02d/%02d/%04d  %-10s  %02d:%02d:%02d          

# MSG_STATE_MENU_DATE_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%02d.%02d.%04d  %-10s  %02d:%02d:%02d          
!%02d.%02d.%04d  %-10s  %02d:%02d:%02d          

# MSG_STATE_MENU_DATE_NONE_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#----/--/--  ----------  --:--:--          
!----/--/--  ----------  --:--:--          

# MSG_STATE_MENU_DATE_NONE_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#--/--/----  ----------  --:--:--          
!--/--/----  ----------  --:--:--          

# MSG_STATE_MENU_DATE_NONE_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#--.--.----  ----------  --:--:--          
!--.--.----  ----------  --:--:--          

# MSG_STATE_MENU_STATE_NONE
#No savestate exists for this slot.
!          $$$Нет сохранённых данных\n\n
!                  $$для этого слота

# MSG_STATE_MENU_TITLE
#Savestate options:
!Настройки сохранений:

# MSG_STATE_MENU_0
#Load savestate from current slot
!Загрузить данные

# MSG_STATE_MENU_1
#Save savestate to current slot
!Сохранить данные

# MSG_STATE_MENU_2
#Load savestate from file
!Загрузить из файла

# MSG_STATE_MENU_3
#Current savestate slot : %d
!Текущий слот : %d

# MSG_STATE_MENU_4
#Back
!Назад

# MSG_STATE_MENU_HELP_0
#Select to load the game state from the current slot for this game.\n
#Press left + right to change the current slot.
!\n\n\n
!Загрузка данных из текущего слота.\n
!Влево/вправо - смена слота.

# MSG_STATE_MENU_HELP_1
#Select to save the game state to the current slot for this game.\n
#Press left + right to change the current slot.
!\n\n\n
!Сохранение данных в текущий слот.\n
!Влево/вправо - смена слота.

# MSG_STATE_MENU_HELP_2
#Restore gameplay from a savestate file.\n
#Note: The same file used to save the state must be present.\n
!\n\n\n\n
!Загрузка данных из внешнего файла.\n

# MSG_STATE_MENU_HELP_3
#Change the current savestate slot.\n
!\n\n\n\n
!Влево/вправо - смена слота.

# MSG_STATE_MENU_HELP_4
#Return to the main menu.
!\n\n\n\n
!Возврат в главное меню.

# MSG_PAD_MENU_0
#D-pad up     : %s
!D-pad вверх   : %s

# MSG_PAD_MENU_1
#D-pad down   : %s
!D-pad вниз    $$: %s

# MSG_PAD_MENU_2
#D-pad left   : %s
!D-pad влево   $$: %s

# MSG_PAD_MENU_3
#D-pad right  : %s
!D-pad вправо $: %s

# MSG_PAD_MENU_4
#Cross        : %s
!Крест            : %s

# MSG_PAD_MENU_5
#Circle       : %s
!Круг             : %s

# MSG_PAD_MENU_6
#Square       : %s
!Квадрат        : %s

# MSG_PAD_MENU_7
#Triangle     : %s
!Треугольник : %s

# MSG_PAD_MENU_8
#Left Trigger : %s
!L-триггер      : %s

# MSG_PAD_MENU_9
#Right Trigger: %s
!R-триггер      : %s

# MSG_PAD_MENU_10
#Start        : %s
!Start            $$$: %s

# MSG_PAD_MENU_11
#Select       : %s
!Select           $$$: %s

# MSG_PAD_MENU_12
#Use default map : %s
!Стандартная раскладка : %s

# MSG_PAD_MENU_13
#Back
!Назад

# MSG_PAD_MENU_HELP_12
#Use default map
!\n\n\n\n
!Раскладка по умолчанию

# MSG_PAD_MENU_HELP_13
#Return to the main menu.
!\n\n\n\n
!Возврат в главное меню.

#Настройка конфигурации PAD

# MSG_PAD_MENU_CFG_0
#UP
!ВВЕРХ

# MSG_PAD_MENU_CFG_1
#DOWN
!ВНИЗ

# MSG_PAD_MENU_CFG_2
#LEFT
!ВЛЕВО

# MSG_PAD_MENU_CFG_3
#RIGHT
!ВПРАВО

# MSG_PAD_MENU_CFG_4
#A
!A

# MSG_PAD_MENU_CFG_5
#B
!B

# MSG_PAD_MENU_CFG_6
#L
!L

# MSG_PAD_MENU_CFG_7
#R
!R

# MSG_PAD_MENU_CFG_8
#START
!START

# MSG_PAD_MENU_CFG_9
#SELECT
!SELECT

# MSG_PAD_MENU_CFG_10
#MENU
!МЕНЮ

# MSG_PAD_MENU_CFG_11
#FASTFORWARD
!FASTFORWARD

# MSG_PAD_MENU_CFG_12
#LOAD STATE
!ЗАГРУЗИТЬ

# MSG_PAD_MENU_CFG_13
#SAVE STATE
!СОХРАНИТЬ

# MSG_PAD_MENU_CFG_14
#RAPIDFIRE A
!TURBO A

# MSG_PAD_MENU_CFG_15
#RAPIDFIRE B
!TURBO B

# MSG_PAD_MENU_CFG_16
#RAPIDFIRE L
!TERBO L

# MSG_PAD_MENU_CFG_17
#RAPIDFIRE R
!TURBO R

# MSG_PAD_MENU_CFG_18
#VOLUME UP
!ГРОМЧЕ

# MSG_PAD_MENU_CFG_19
#VOLUME DOWN
!ТИШЕ

# MSG_PAD_MENU_CFG_20
#DISPLAY FPS
!ПОКАЗ FPS

# MSG_PAD_MENU_CFG_21
#NOTHING
!НИЧЕГО

# MSG_PAD_MENU_CFG_HELP_0
#Up button on GBA d-pad.
!\n\n\n\n
!Кнопка "ВВЕРХ" GBA.

# MSG_PAD_MENU_CFG_HELP_1
#Down button on GBA d-pad.
!\n\n\n\n
!Кнопка "ВНИЗ" GBA.

# MSG_PAD_MENU_CFG_HELP_2
#Left button on GBA d-pad.
!\n\n\n\n
!Кнопка "ВЛЕВО" GBA.

# MSG_PAD_MENU_CFG_HELP_3
#Right button on GBA d-pad.
!\n\n\n\n
!Кнопка "ВПРАВО" GBA.

# MSG_PAD_MENU_CFG_HELP_4
#A button on GBA.
!\n\n\n\n
!Кнопка "A" GBA.

# MSG_PAD_MENU_CFG_HELP_5
#B button on GBA.
!\n\n\n\n
!Кнопка "B" GBA.

# MSG_PAD_MENU_CFG_HELP_6
#Left shoulder button on GBA.
!\n\n\n\n
!Левый триггер GBA.

# MSG_PAD_MENU_CFG_HELP_7
#Right shoulder button on GBA.
!\n\n\n\n
!Правый триггер GBA.

# MSG_PAD_MENU_CFG_HELP_8
#Start button on GBA.
!\n\n\n\n
!Кнопка "START" GBA.

# MSG_PAD_MENU_CFG_HELP_9
#Select button on GBA.
!\n\n\n\n
!Кнопка "SELECT" GBA.

# MSG_PAD_MENU_CFG_HELP_10
#Brings up the options menu.
!\n\n\n\n
!Переход в меню настроек.

# MSG_PAD_MENU_CFG_HELP_11
#Toggles fastforward on/off (don't expect it to do much or anything)
!\n\n\n\n
!Переключает ускоренную перемотку вперед вкл/выкл.

# MSG_PAD_MENU_CFG_HELP_12
#Loads the game state from the current slot.
!\n\n\n\n
!Загрузка из текущего слота.

# MSG_PAD_MENU_CFG_HELP_13
#Saves the game state to the current slot.
!\n\n\n\n
!Сохранение в текущий слот.

# MSG_PAD_MENU_CFG_HELP_14
#Rapidly press/release the A button on GBA.
!\n\n\n\n
!Многократное нажатие кнопки "A" GBA.

# MSG_PAD_MENU_CFG_HELP_15
#Rapidly press/release the B button on GBA.
!\n\n\n\n
!Многократное нажатие кнопки "B" GBA.

# MSG_PAD_MENU_CFG_HELP_16
#Rapidly press/release the L shoulder button on GBA.
!\n\n\n\n
!Многократное нажатие левого триггера GBA.

# MSG_PAD_MENU_CFG_HELP_17
#Rapidly press/release the R shoulder button on GBA.
!\n\n\n\n
!Многократное нажатие правого триггера GBA.

# MSG_PAD_MENU_CFG_HELP_18
#Increases the volume.
!\n\n\n\n
!Увеличить громкость.

# MSG_PAD_MENU_CFG_HELP_19
#Decreases the volume.
!\n\n\n\n
!Уменьшить громкость.

# MSG_PAD_MENU_CFG_HELP_20
#Displays virtual/drawn frames per second.
!\n\n\n\n
!Отображение счётчика кадров в секунду.

# MSG_PAD_MENU_CFG_HELP_21
#Does nothing.
!\n\n\n\n
!Никаких действий.

# MSG_A_PAD_MENU_0
#Analog up   : %s
!Аналог вверх  $$$: %s

# MSG_A_PAD_MENU_1
#Analog down : %s
!Аналог вниз    $: %s

# MSG_A_PAD_MENU_2
#Analog left : %s
!Аналог влево   $: %s

# MSG_A_PAD_MENU_3
#Analog right: %s
!Аналог вправо : %s

# MSG_A_PAD_MENU_4
#Enable analog: %s
!Аналог включён   $$$: %s

# MSG_A_PAD_MENU_5
#Analog sensitivity: %d
!Чувствительность : %d

# MSG_A_PAD_MENU_6
#Tilt sensor : %s
!Датчик наклона   $$: %s

# MSG_A_PAD_MENU_7
#Back
!Назад

# MSG_A_PAD_MENU_HELP_0
#Select 'no' to block analog input entirely.
!\n\n\n\n
!Выберите "нет" для отключения аналога.

# MSG_A_PAD_MENU_HELP_1
#Determine sensitivity/responsiveness of the analog input.\n
#Lower numbers are less sensitive.
!\n\n\n
!Настройка чувствительности аналогового ввода.\n
!Меньшее значение - ниже чувствительность.

# MSG_A_PAD_MENU_HELP_2
#Tilt sensor
!\n\n\n\n
!Датчик наклона

# MSG_A_PAD_MENU_HELP_3
#Return to the main menu.
!\n\n\n\n
!Возврат в главное меню.

# MSG_CHEAT_MENU_NON_LOAD
#cheat %d (none loaded)
!Чит %d (не загружен)

# MSG_CHEAT_MENU_0
#cheat %d (%s): %%s
!Чит %d (%s): %%s

# MSG_CHEAT_MENU_1
#Load Cheat File
!Загрузить чит

# MSG_CHEAT_MENU_2
#Clock speed: %s
!Частота ЦП         $$: %s

# MSG_CHEAT_MENU_3
#Update backup: %s
!Сохранять бэкап : %s

# MSG_CHEAT_MENU_4
#Back
!Назад

# MSG_CHEAT_MENU_HELP_0
#Activate/deactivate this cheat code.
!\n\n\n\n
!Включить/выключить чит-коды.

# MSG_CHEAT_MENU_HELP_1
# Load Cheat File
!\n\n\n\n
!Загрузка файла с читом

# MSG_CHEAT_MENU_HELP_2
#Change the clock speed of the device. Higher clock speed will yield\n
#better performance, but will use drain battery life further.
!\n\n\n
!Изменение частоты процессора.\n
!Выше частота - быстрее эмуляция и меньше жизнь батареи.

# MSG_CHEAT_MENU_HELP_3
#Determines when in-game save files should be written back to\n
#memstick. If set to 'automatic' writebacks will occur shortly after\n
#the game's backup is altered. On 'exit only' it will only be written\n
#back when you exit from this menu (NOT from using the home button).\n
#Use the latter with extreme care.
!\n\n
!Настройка сохранения внутренних данных игры на карту памяти.\n
!Авто - автоматичесое сохранени данных\n
!На выходе - при выходе из эмуляции

# MSG_CHEAT_MENU_HELP_4
#Return to the main menu.
!\n\n\n\n
!Возврат в главное меню.

# MSG_MISC_MENU_0
#Emulate Core : %s
!Эмуляция ядра   : %s

# MSG_MISC_MENU_1
#Debug mode : %s
!Дебаг режим       $$$: %s

# MSG_MISC_MENU_2
#Language : %s
!Язык : %s

# MSG_MISC_MENU_3
#Fake Fat : %s
!Ложная ФАТ       : %s

# MSG_MISC_MENU_4
#Boot Mode : %s
!Режим загрузки : %s

# MSG_MISC_MENU_5
#Brightness : %d
!Яркость : %d

# MSG_MISC_MENU_HELP_0
#Emulate Core
!\n\n\n\n
!Эмуляция ядра

# MSG_MISC_MENU_HELP_1
#Debug mode
!\n\n\n\n
!Дебаг режим

# MSG_MISC_MENU_HELP_2
#Language
!\n\n\n\n
!Выбор языка меню

# MSG_MISC_MENU_HELP_3
#Fake Fat
!\n\n\n\n
!Фейковая ФАТка

# MSG_MISC_MENU_HELP_4
#Boot Mode
!\n\n\n\n
!Режим загрузки

# MSG_MISC_MENU_HELP_5
#Brightness
!\n\n\n\n
!Яркость

# MSG_NON_LOAD_GAME
#No game loaded yet.
!               $$$Игра не загружена

# MSG_WDAY_0
#Sunday
!Воскресенье

# MSG_WDAY_1
#Monday
!Понедельник

# MSG_WDAY_2
#Tuesday
!Вторник

# MSG_WDAY_3
#Wednesday
!Среда

# MSG_WDAY_4
#Thursday
!Четверг

# MSG_WDAY_5
#Friday
!Пятница

# MSG_WDAY_6
#Saturday
!Суббота

# MSG_YES
#yes
!да

# MSG_NO
#no
!нет

# MSG_YES_NO
#Yes - X / No - O
!Да - X / Нет - O

# MSG_ENABLED
#enabled
!включен

# MSG_DISABLED
#disabled
!отключен

# MSG_SCALE_UNSCALED
#unscaled 3:2
!оригинал 3:2

# MSG_SCALE_SCALED
#scaled 3:2
!масштаб 3:2

# MSG_SCALE_FULL
#fullscreen 16:9
!полный 16:9

# MSG_SCN_OPT1
#option 1
!опция 1

# MSG_SCN_OPT2
#option 2
!опция 2

# MSG_FS_AUTO
#automatic
!авто

# MSG_FS_MANUAL
#manual
!точно

# MSG_FS_OFF
#off
!отключен

# MSG_FS_UNIFORM
#uniform
!универсально

# MSG_FS_RAMDOM
#random
!случайно

# MSG_SB_2048
#2048 bytes
!2048 байт

# MSG_SB_3072
#3072 bytes
!3072 байт

# MSG_SB_4096
#4096 bytes
!4096 байт

# MSG_SB_5120
#5120 bytes
!5120 байт

# MSG_SB_6144
#6144 bytes
!6144 байт

# MSG_SB_7168
#7168 bytes
!7168 байт

# MSG_SB_8192
#8192 bytes
!8192 байт

# MSG_SB_9216
#9216 bytes
!9216 байт

# MSG_SB_10240
#10240 bytes
!10240 байт

# MSG_SB_11264
#11264 bytes
!11264 байт

# MSG_SB_12288
#12288 bytes
!12288 байт

# MSG_BK_EXITONLY
#Exit only
!на выходе

# MSG_BK_AUTO
#Automatic
!Авто

# MSG_CLK_33
#33MHz
!33MHz

# MSG_CLK_66
#66MHz
!66MHz

# MSG_CLK_100
#100MHz
!100MHz

# MSG_CLK_133
#133MHz
!133MHz

# MSG_CLK_166
#166MHz
!166MHz

# MSG_CLK_200
#200MHz
!200MHz

# MSG_CLK_233
#233MHz
!233MHz

# MSG_CLK_266
#266MHz
!266MHz

# MSG_CLK_300
#300MHz
!300MHz

# MSG_CLK_333
#333MHz
!333MHz

# MSG_SS_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%04d_%02d_%02d_%s%02d_%02d_%02d_%03d
!%04d_%02d_%02d_%s%02d_%02d_%02d_%03d

# MSG_SS_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%s%02d_%02d_%04d_%02d_%02d_%02d_%03d
!%s%02d_%02d_%04d_%02d_%02d_%02d_%03d

# MSG_SS_FMT_3
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%s%02d_%02d_%04d_%02d_%02d_%02d_%03d
!%s%02d_%02d_%04d_%02d_%02d_%02d_%03d

# MSG_ERR_BIOS_1
#Sorry, but gpSP requires a Gameboy Advance BIOS image to run\n
#correctly. Make sure to get an authentic one (search the web,\n
#beg other people if you want, but don't hold me accountable\n
#if you get hated or banned for it), it'll be exactly 16384\n
#bytes large and should have the following md5sum value:\n\n
!Sorry, but gpSP requires a Gameboy Advance BIOS image to run\n
!correctly. Make sure to get an authentic one (search the web,\n
!beg other people if you want, but don't hold me accountable\n
!if you get hated or banned for it), it'll be exactly 16384\n
!bytes large and should have the following md5sum value:\n\n

# MSG_ERR_BIOS_2
#a860e8c0b6d573d191e4ec7db1b1e4f6 or 1c0d67db9e1208b95a1506b1688a0ad6\n\n
#Other BIOS files might work either partially completely, I\n
#really don't know.\n\n
#When you do get it name it gba_bios.bin and put it in the\n
#same directory as this EBOOT.\n\n
#Good luck. Press any button to exit.\n
!a860e8c0b6d573d191e4ec7db1b1e4f6 or 1c0d67db9e1208b95a1506b1688a0ad6\n\n
!Other BIOS files might work either partially completely, I\n
!really don't know.\n\n
!When you do get it name it gba_bios.bin and put it in the\n
!same directory as this EBOOT.\n\n
!Good luck. Press any button to exit.\n

# MSG_ERR_BIOS_MD5
#This BIOS is not regular.\n
#There is a possibility of various trouble.\n\n
#Please use regular BIOS.\n
!This BIOS is not regular.\n
!There is a possibility of various trouble.\n\n
!Please use regular BIOS.\n

# MSG_R_4_3
#ratio 4:3
!4:3

# MSG_R_16_9
#ratio 16:9
!16:9

# MSG_I_NON
#progressive
!построчно

# MSG_I_ON
#interlace
!интерлейс

# MSG_INIT_END
#Initialization end
!Эмулятор запущен

# MSG_LOAD_STATE
#Load State.
!Загрузка сохранения.

# MSG_LOAD_STATE_END
#Load State End.
!Сохранение загружено.

# MSG_SAVE_STATE
#Save State.
!Сохранение игры.

# MSG_SAVE_STATE_END
#Save State End.
!Игра сохранена.

# MSG_LOAD_STATE_No
#Load State No: %d
!Загрузка сохранения из слота №%d

# MSG_SAVE_STATE_No
#Save State No: %d
!Сохранение игры в слот №%d

# MSG_LOAD_ZIP_ROM
#Load ZIP ROM.
!Загружается ZIP ROM.

# MSG_LOAD_ROM
#Load ROM.
!Загружается ROM.

# MSG_LOAD_ROM_OK
#Load ROM OK.
!ROM успешно загружен.

# MSG_CHEAT_MENU_5
#Cheat page: %d
!Страница читов : %d

# MSG_CHEAT_MENU_HELP_5
#Cheat page
!\n\n\n\n
!Страница читов

# MSG_CHEAT_MENU_6
#Enable HOME: %s
!Включить "HOME"  $$: %s

# MSG_CHEAT_MENU_HELP_6
#Enable HOME
!\n\n\n\n
!Стандартная функция кнопки "HOME"
