# messege file
# Spanish

#To align text, use the following information: symbol "space" = 4 pixels; symbol "$" = 1 pixel.

# MSG_RETURN_MENU
#Press O to return to the main menu.
!Pulsa O para volver al menú principal.

# MSG_MENU_DATE
#TIME 
!

# MSG_MENU_BATTERY
#battery LifePercent: %3d%% LifeTime:%3d min
!Porcentaje bateria: %3d%% Duracion:%3d min

# MSG_DATE_FMT_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%04d/%02d/%02d  %-10s  %02d:%02d:%02d          
!%04d/%02d/%02d  %-10s  %02d:%02d:%02d          

# MSG_DATE_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%02d/%02d/%04d  %-10s  %02d:%02d:%02d          
!%02d/%02d/%04d  %-10s  %02d:%02d:%02d          

# MSG_DATE_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%02d.%02d.%04d  %-10s  %02d:%02d:%02d          
!%02d.%02d.%04d  %-10s  %02d:%02d:%02d          

# MSG_MAIN_MENU_0
#Graphics and Sound options
!Opciones de Gráficos y Sonido

# MSG_MAIN_MENU_1
#Load state from slot: %d
!Cargar partida de Slot   $$: %d

# MSG_MAIN_MENU_2
#Save state to slot: %d
!Guardar partida en Slot : %d

# MSG_MAIN_MENU_3
#Savestate options
!Opciones partidas guardadas

# MSG_MAIN_MENU_4
#Configure gamepad input
!Configurar controles

# MSG_MAIN_MENU_5
#Configure analog input
!Configurar PAD analógico

# MSG_MAIN_MENU_6
#Cheats Manager
!Trucos y Otras opciones

# MSG_MAIN_MENU_7
#Load new game
!Cargar nuevo Juego

# MSG_MAIN_MENU_8
#Restart game
!Resetear Juego

# MSG_MAIN_MENU_9
#Return to game
!Volver al Juego

# MSG_MAIN_MENU_10
#Exit gpSP
!Salir

# MSG_MAIN_MENU_11
#Language and other options
!Idiomas y otras opciones

# MSG_MAIN_MENU_HELP_0
#Select to set display parameters and frameskip behavior,\n
#audio on/off, audio buffer size, and audio filtering.
!\n\n\n
!Modifica las opciones de pantalla y el salto de frames,\n
!audio on/off, cantidad de buffer de audio, y filtrado de audio.

# MSG_MAIN_MENU_HELP_1
#Select to load the game state from the current slot for this game,\n
#if it exists (see the extended menu for more information)\n
#Press left + right to change the current slot.
!\n\n
!Carga la partida guardada del Slot actual para este juego,\n
!si existe (ver el menu extendido para mas informacion)\n
!Pulsa izquierda o derecha para cambiar el Slot actual.

# MSG_MAIN_MENU_HELP_2
#Select to save the game state to the current slot for this game.\n
#See the extended menu for more information.\n
#Press left + right to change the current slot.
!\n\n
!Graba la partida en el Slot actual para este juego.\n
!Ver el menu extendido para mas informacion.\n
!Pulsa izquierda o derecha para cambiar el Slot actual.

# MSG_MAIN_MENU_HELP_3
#Select to enter a menu for loading, saving, and viewing the\n
#currently active savestate for this game (or to load a savestate\n
#file from another game)
!\n\n\n
!Entra al menu para cargar, salvar y ver las partidas guardadas\n
!para este juego (o para cargar una partidade otro juego).

# MSG_MAIN_MENU_HELP_4
#Select to change the in-game behavior of the PSP buttons and d-pad.
!\n\n\n\n
!Cambia el comportamiento durante el juego de los botones y el PAD.

# MSG_MAIN_MENU_HELP_5
#Select to change the in-game behavior of the PSP analog nub.
!\n\n\n\n
!Cambia el comportamiento durante el juego del Stick analogico.

# MSG_MAIN_MENU_HELP_6
#Select to manage cheats.
!\n\n\n\n
!Administra trucos

# MSG_MAIN_MENU_HELP_7
#Select to load a new game (will exit a game if currently playing).
!\n\n\n\n
!Carga un nuevo juego (si estas jugando saldras del juego actual).

# MSG_MAIN_MENU_HELP_8
#Select to reset the GBA with the current game loaded.
!\n\n\n\n
!Resetea la GBA con el juego actual insertado.

# MSG_MAIN_MENU_HELP_9
#Select to exit this menu and resume gameplay.
!\n\n\n\n
!Sal de este menu y vuelve al juego.

# MSG_MAIN_MENU_HELP_10
#Select to exit gpSP and return to the PSP XMB/loader.
!\n\n\n\n
!Sal del gpSP y vuelve al XMB.

# MSG_MAIN_MENU_HELP_11
#Languages, set backup behavior, and set device clock speed.
!\n\n\n
!Idiomas y varios disparos, comportamiento\n
!de las ROMs y la velocidad de la CPU.

# MSG_SCALE
#Display scaling: %s
!Escalado Pantalla      $$: %s

# MSG_FILTER
#Screen filtering: %s
!Filtrado Pantalla       : %s

# MSG_RATIO
#TV output ratio: %s
!Escala salida TV         : %s

# MSG_INTERLACE
#TV output interlace: %s
!Entrelazado salida TV : %s

# MSG_SKIP_TYPE
#Frameskip type: %s
!Tipo Frameskip        $: %s

# MSG_SKIP_VALUE
#Frameskip value: %d
!Valor Frameskip       : %d

# MSG_SKIP_RANDOM
#Framskip variation: %s
!Variacion Frameskip : %s

# MSG_AUDIO_ENABLE
#Audio output: %s
!Salida Audio  : %s

# MSG_AUDIO_BUFFER
#Audio buffer: %s
!Buffer Audio : %s

# MSG_SCREEN_SHOT
#Screen shot
!Captura de Pantalla

# MSG_DISPLAY_SCALE
#Scale: %d
!Escala : %d

# MSG_MENU_RETURN_MAIN
#Back
!Atras

# MSG_G_S_MENU_HELP_0
#Determines how the GBA screen is resized in relation to the entire\n
#screen. Select unscaled 3:2 for GBA resolution, scaled 3:2 for GBA\n
#aspect ratio scaled to fill the height of the PSP screen, and\n
#fullscreen to fill the entire PSP screen.
!\n
!Determina como se redimensiona la pantalla de la GBA en relacion a la\n
!de la PSP. Sin escalar 3:2 da la resolucion de GBA, pon escalado 3:2 para\n
!resolucion de GBA ajustada al alto de la pantalla PSP, y\n
!pantalla completa para llenar la pantalla de la PSP.

# MSG_G_S_MENU_HELP_1
#Determines whether or not bilinear filtering should be used when\n
#scaling the screen. Selecting this will produce a more even and\n
#smooth image, at the cost of being blurry and having less vibrant\n
#colors.
!\n\n
!Determina si se usa o no el filtrado bilinear cuando se escala\n
!la pantalla. Ofrece una imagen mas suave, a costa de estar\n
!un poco mas borrosa y tener colores menos vivos.

# MSG_G_S_MENU_HELP_2
#Determines what kind of frameskipping should be employed.\n
#Frameskipping may improve emulation speed of many games.\n
#Off: Do not skip any frames.\n
#Auto: Skip up to N frames (see next option) as needed.\n
#Manual: Always render only 1 out of N + 1 frames.
!\n
!Determina que tipo de salto de frames se utiliza.\n
!El salto de frames puede mejorar la velocidad de emulacion.\n
!Off: No se saltan frames.\n
!Auto: Se saltan N frames (ver la siguiente opcion) segun se necesite.\n
!Manual: Siempre se renderizan 1 de N + 1 frames.

# MSG_G_S_MENU_HELP_3
#For auto frameskip, determines the maximum number of frames that\n
#are allowed to be skipped consecutively.\n
#For manual frameskip, determines the number of frames that will\n
#always be skipped.
!\n
!Para salto de frames automatico, determina el maximo numero\n
!de frames que se permiten saltar consecutivamente.\n
!Para el salto de frames manual, determina el numero\n
!de frames quesiempre se saltan.

# MSG_G_S_MENU_HELP_4
#If objects in the game flicker at a regular rate certain manual\n
#frameskip values may cause them to normally disappear. Change this\n
#value to 'random' to avoid this. Do not use otherwise, as it tends to\n
#make the image quality worse, especially in high motion games.
!\n
!Si los objetos en el juego parpadean con frecuencia, algunos valores\n
!de frameskip manual pueden hacer que desaparezcan. Cambia este valor\n
!a 'aleatorio' para evitar esto. No lo uses de otro modo, ya que empeorara\n
!la calidad de la imagen, especialmente en juegos con mucho movimiento.

# MSG_G_S_MENU_HELP_5
#Select 'no' to turn off all audio output. This will not result in a\n
#significant change in performance.
!\n\n\n
!Seleciona 'no' para desactivar el audio.\n
!No mejorara significativamente el rendimiento.

# MSG_G_S_MENU_HELP_6
#Set the size (in bytes) of the audio buffer. Larger values may result\n
#in slightly better performance at the cost of latency; the lowest\n
#value will give the most responsive audio.\n
#This option requires gpSP to be restarted before it will take effect.
!\n
!Establece el espacio (en bytes) del buffer de audio. Valores mas grandes\n
!pueden mejorar el rendimiento a costa de latencia; valores menores\n
!daran una respuesta mas sensible del audio.\n
!Esta opcion necesita que reinicies gpSP para que surta efecto.

# MSG_G_S_MENU_HELP_7
#Screen shot
!\n\n\n\n
!Captura de Pantalla

# MSG_G_S_MENU_HELP_8
#Return to the main menu.
!\n\n\n\n
!Volver al menu principal.

# MSG_G_S_MENU_HELP_9
#TV output ratio
!\n\n\n\n
!Escala salida TV

# MSG_G_S_MENU_HELP_10
#Scaling
!\n\n\n\n
!Escala

# MSG_G_S_MENU_HELP_11
#TV output interlace
!\n\n\n\n
!Entrelazado salida TV

# MSG_STATE_MENU_DATE_FMT_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%04d/%02d/%02d  %-10s  %02d:%02d:%02d          
!%04d/%02d/%02d  %-10s  %02d:%02d:%02d          

# MSG_STATE_MENU_DATE_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%02d/%02d/%04d  %-10s  %02d:%02d:%02d          
!%02d/%02d/%04d  %-10s  %02d:%02d:%02d          

# MSG_STATE_MENU_DATE_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%02d.%02d.%04d  %-10s  %02d:%02d:%02d          
!%02d.%02d.%04d  %-10s  %02d:%02d:%02d          

# MSG_STATE_MENU_DATE_NONE_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#----/--/--  ----------  --:--:--          
!----/--/--  ----------  --:--:--          

# MSG_STATE_MENU_DATE_NONE_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#--/--/----  ----------  --:--:--          
!--/--/----  ----------  --:--:--          

# MSG_STATE_MENU_DATE_NONE_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#--.--.----  ----------  --:--:--          
!--.--.----  ----------  --:--:--          

# MSG_STATE_MENU_STATE_NONE
#No savestate exists for this slot.
!           $No existe partida guardada\n\n
!                    para este Slot

# MSG_STATE_MENU_TITLE
#Savestate options:
!Opciones de partidas guardadas:

# MSG_STATE_MENU_0
#Load savestate from current slot
!Cargar partida del Slot actual

# MSG_STATE_MENU_1
#Save savestate to current slot
!Salvar partida en el Slot actual

# MSG_STATE_MENU_2
#Load savestate from file
!Cargar partida desde archivo

# MSG_STATE_MENU_3
#Current savestate slot: %d
!Slot actual : %d

# MSG_STATE_MENU_4
#Back
!Atras

# MSG_STATE_MENU_HELP_0
#Select to load the game state from the current slot for this game.\n
#Press left + right to change the current slot.
!\n\n\n
!Carga la partida del Slot actual para este juego.\n
!Pulsa izquierda o derecha para cambiar el Slot actual.

# MSG_STATE_MENU_HELP_1
#Select to save the game state to the current slot for this game.\n
#Press left + right to change the current slot.
!\n\n\n
!Salva la partida en el Slot actual para este juego.\n
!Pulsa izquierda o derecha para cambiar el Slot actual.

# MSG_STATE_MENU_HELP_2
#Restore gameplay from a savestate file.\n
#Note: The same file used to save the state must be present.\n
!\n\n\n
!Restaura una partida desde un archivo guardado.\n
!Nota: El mismo archivo usado para grabar debe estar presente.\n

# MSG_STATE_MENU_HELP_3
#Change the current savestate slot.\n
!\n\n\n\n
!Cambia el Slot actual.\n

# MSG_STATE_MENU_HELP_4
#Return to the main menu.
!\n\n\n\n
!Volver al menu principal.

# MSG_PAD_MENU_0
#D-pad up: %s
!D-pad arriba   $$: %s

# MSG_PAD_MENU_1
#D-pad down: %s
!D-pad abajo    $$$: %s

# MSG_PAD_MENU_2
#D-pad left: %s
!D-pad izqda    $$$: %s

# MSG_PAD_MENU_3
#D-pad right: %s
!D-pad derecha : %s

# MSG_PAD_MENU_4
#Cross: %s
!Cruzar           : %s

# MSG_PAD_MENU_5
#Circle: %s
!Circulo          $$: %s

# MSG_PAD_MENU_6
#Square: %s
!Cuadrado        : %s

# MSG_PAD_MENU_7
#Triangle: %s
!Triangulo       : %s

# MSG_PAD_MENU_8
#Left Trigger: %s
!L-Trigger       $$$: %s

# MSG_PAD_MENU_9
#Right Trigger: %s
!R-Trigger       $$$: %s

# MSG_PAD_MENU_10
#Start: %s
!Start             : %s

# MSG_PAD_MENU_11
#Select: %s
!Select            : %s

# MSG_PAD_MENU_12
#Use default map: %s
!Usar controles por defecto : %s

# MSG_PAD_MENU_13
#Back
!Atras

# MSG_PAD_MENU_HELP_12
#Use default map
!\n\n\n\n
!Usar controles por defecto

# MSG_PAD_MENU_HELP_13
#Return to the main menu.
!\n\n\n\n
!Volver al menu principal.

#Settings configuration PAD

# MSG_PAD_MENU_CFG_0
#UP
!ARRIBA

# MSG_PAD_MENU_CFG_1
#DOWN
!ABAJO

# MSG_PAD_MENU_CFG_2
#LEFT
!IZQUIERDA

# MSG_PAD_MENU_CFG_3
#RIGHT
!DERECHA

# MSG_PAD_MENU_CFG_4
#A
!A

# MSG_PAD_MENU_CFG_5
#B
!B

# MSG_PAD_MENU_CFG_6
#L
!L

# MSG_PAD_MENU_CFG_7
#R
!R

# MSG_PAD_MENU_CFG_8
#START
!START

# MSG_PAD_MENU_CFG_9
#SELECT
!SELECT

# MSG_PAD_MENU_CFG_10
#MENU
!MENU

# MSG_PAD_MENU_CFG_11
#FASTFORWARD
!AVANCERAPIDO

# MSG_PAD_MENU_CFG_12
#LOAD STATE
!CARGA PARTIDA

# MSG_PAD_MENU_CFG_13
#SAVE STATE
!GUARDA PARTIDA

# MSG_PAD_MENU_CFG_14
#RAPIDFIRE A
!FUEGORAPIDO A

# MSG_PAD_MENU_CFG_15
#RAPIDFIRE B
!FUEGORAPIDO B

# MSG_PAD_MENU_CFG_16
#RAPIDFIRE L
!FUEGORAPIDO L

# MSG_PAD_MENU_CFG_17
#RAPIDFIRE R
!FUEGORAPIDO R

# MSG_PAD_MENU_CFG_18
#VOLUME UP
!VOLUMEN MAS

# MSG_PAD_MENU_CFG_19
#VOLUME DOWN
!VOLUMEN MENOS

# MSG_PAD_MENU_CFG_20
#DISPLAY FPS
!MUESTRA FPS

# MSG_PAD_MENU_CFG_21
#NOTHING
!NADA

# MSG_PAD_MENU_CFG_HELP_0
#Up button on GBA d-pad.
!\n\n\n\n
!Arriba en el PAD GBA.

# MSG_PAD_MENU_CFG_HELP_1
#Down button on GBA d-pad.
!\n\n\n\n
!Abajo en el PAD GBA.

# MSG_PAD_MENU_CFG_HELP_2
#Left button on GBA d-pad.
!\n\n\n\n
!Izquierda en el PAD GBA.

# MSG_PAD_MENU_CFG_HELP_3
#Right button on GBA d-pad.
!\n\n\n\n
!Derecha en el PAD GBA.

# MSG_PAD_MENU_CFG_HELP_4
#A button on GBA.
!\n\n\n\n
!A en GBA.

# MSG_PAD_MENU_CFG_HELP_5
#B button on GBA.
!\n\n\n\n
!B en GBA.

# MSG_PAD_MENU_CFG_HELP_6
#Left shoulder button on GBA.
!\n\n\n\n
!L en GBA.

# MSG_PAD_MENU_CFG_HELP_7
#Right shoulder button on GBA.
!\n\n\n\n
!R en GBA.

# MSG_PAD_MENU_CFG_HELP_8
#Start button on GBA.
!\n\n\n\n
!Start en GBA.

# MSG_PAD_MENU_CFG_HELP_9
#Select button on GBA.
!\n\n\n\n
!Select en GBA.

# MSG_PAD_MENU_CFG_HELP_10
#Brings up the options menu.
!\n\n\n\n
!Muestra el menu de opciones.

# MSG_PAD_MENU_CFG_HELP_11
#Toggles fastforward on/off (don't expect it to do much or anything)
!\n\n\n\n
!Avance rapido on/off (no siempre funciona)

# MSG_PAD_MENU_CFG_HELP_12
#Loads the game state from the current slot.
!\n\n\n\n
!Carga la partida del Slot actual.

# MSG_PAD_MENU_CFG_HELP_13
#Saves the game state to the current slot.
!\n\n\n\n
!Guarda la partida en el Slot actual.

# MSG_PAD_MENU_CFG_HELP_14
#Rapidly press/release the A button on GBA.
!\n\n\n\n
!Pulsa/Suelta rapidamente el boton A en GBA.

# MSG_PAD_MENU_CFG_HELP_15
#Rapidly press/release the B button on GBA.
!\n\n\n\n
!Pulsa/Suelta rapidamente el boton B en GBA.

# MSG_PAD_MENU_CFG_HELP_16
#Rapidly press/release the L shoulder button on GBA.
!\n\n\n\n
!Pulsa/Suelta rapidamente el boton L en GBA.

# MSG_PAD_MENU_CFG_HELP_17
#Rapidly press/release the R shoulder button on GBA.
!\n\n\n\n
!Pulsa/Suelta rapidamente el boton R en GBA.

# MSG_PAD_MENU_CFG_HELP_18
#Increases the volume.
!\n\n\n\n
!Aumenta el volumen.

# MSG_PAD_MENU_CFG_HELP_19
#Decreases the volume.
!\n\n\n\n
!Disminuye el volumen.

# MSG_PAD_MENU_CFG_HELP_20
#Displays virtual/drawn frames per second.
!\n\n\n\n
!Muestra los frames por segundo.

# MSG_PAD_MENU_CFG_HELP_21
#Does nothing.
!\n\n\n\n
!No hace nada.

# MSG_A_PAD_MENU_0
#Analog up: %s
!Analog arrib  : %s

# MSG_A_PAD_MENU_1
#Analog down: %s
!Analog abajo $$$: %s

# MSG_A_PAD_MENU_2
#Analog left: %s
!Analog izqda $$$: %s

# MSG_A_PAD_MENU_3
#Analog right: %s
!Analog drcha : %s

# MSG_A_PAD_MENU_4
#Enable analog: %s
!Habilita el Analogico        $$: %s

# MSG_A_PAD_MENU_5
#Analog sensitivity: %d
!Sensibilidad del Analogico : %d

# MSG_A_PAD_MENU_6
#Tilt sensor : %s
!Tilt sensor                     : %s

# MSG_A_PAD_MENU_7
#Back
!Atras

# MSG_A_PAD_MENU_HELP_0
#Select 'no' to block analog input entirely.
!\n\n\n\n
!Selecciona 'no' para deshabilitar el analogico.

# MSG_A_PAD_MENU_HELP_1
#Determine sensitivity/responsiveness of the analog input.\n
#Lower numbers are less sensitive.
!\n\n\n
!Determina la sensibilidad/respuesta del control analogico.\n
!Numeros mas bajos son menos sensibles.

# MSG_A_PAD_MENU_HELP_2
#Tilt sensor
!\n\n\n\n
!Tilt sensor

# MSG_A_PAD_MENU_HELP_3
#Return to the main menu.
!\n\n\n\n
!Volver al menu principal.

# MSG_CHEAT_MENU_NON_LOAD
#cheat %d (none loaded)
!truco %d (ninguno cargado)

# MSG_CHEAT_MENU_0
#cheat %d (%s): %%s
!truco %d (%s): %%s

# MSG_CHEAT_MENU_1
#Load Cheat File
!Carga Archivo de Trucos

# MSG_CHEAT_MENU_2
#Clock speed: %s
!Velocidad CPU   : %s

# MSG_CHEAT_MENU_3
#Update backup: %s
!Actualizar ROM : %s

# MSG_CHEAT_MENU_4
#Back
!Atras

# MSG_CHEAT_MENU_HELP_0
#Activate/deactivate this cheat code.
!\n\n\n\n
!Activar/desactivar este truco.

# MSG_CHEAT_MENU_HELP_1
# Load Cheat File
!\n\n\n\n
! Carga Archivo de Trucos

# MSG_CHEAT_MENU_HELP_2
#Change the clock speed of the device. Higher clock speed will yield\n
#better performance, but will use drain battery life further.
!\n\n\n
!Cambia la velocidad de la CPU.\n
!Cuanto mas alta mas rendimiento, pero la bateria durara menos.

# MSG_CHEAT_MENU_HELP_3
#Determines when in-game save files should be written back to\n
#memstick. If set to 'automatic' writebacks will occur shortly after\n
#the game's backup is altered. On 'exit only' it will only be written\n
#back when you exit from this menu (NOT from using the home button).\n
#Use the latter with extreme care.
!\n
!Determina si las partidas guardadas mientras juegas deberian ser reescritas\n
!a la Memory Stick. Si lo tenemos en 'automatico' se escribiran cuando la ROM\n
!se modifica. 'solo al salir' hara que solo se escriban cuando sales de este\n
!menu (pero NO usando el boton Home). Usa lo ultimo con mucho cuidado.

# MSG_CHEAT_MENU_HELP_4
#Return to the main menu.
!\n\n\n\n
!Volver al menu principal.

# MSG_MISC_MENU_0
#Emulate Core: %s
!Emulate Core : %s

# MSG_MISC_MENU_1
#Debug mode: %s
!Debug mode : %s

# MSG_MISC_MENU_2
#Language: %s
!Idioma : %s

# MSG_MISC_MENU_3
#Fake Fat: %s
!Falso Fat $$: %s

# MSG_MISC_MENU_4
#Boot Mode: %s
!Modo bota : %s

# MSG_MISC_MENU_5
#Brightness: %d
!Brightness : %d

# MSG_MISC_MENU_HELP_0
#Emulate Core
!\n\n\n\n
!Emulate Core

# MSG_MISC_MENU_HELP_1
#Debug mode
!\n\n\n\n
!Debug mode

# MSG_MISC_MENU_HELP_2
#Language
!\n\n\n\n
!Emulador menu de idioma

# MSG_MISC_MENU_HELP_3
#Fake Fat
!\n\n\n\n
!Falso Fat

# MSG_MISC_MENU_HELP_4
#Boot Mode
!\n\n\n\n
!Modo bota

# MSG_MISC_MENU_HELP_5
#Brightness
!\n\n\n\n
!Brightness

# MSG_NON_LOAD_GAME
#No game loaded yet
!           $$Aun no hay juego cargado

# MSG_WDAY_0
#Sunday
!Domingo

# MSG_WDAY_1
#Monday
!Lunes

# MSG_WDAY_2
#Tuesday
!Martes

# MSG_WDAY_3
#Wednesday
!Miercoles

# MSG_WDAY_4
#Thursday
!Jueves

# MSG_WDAY_5
#Friday
!Viernes

# MSG_WDAY_6
#Saturday
!Sabado

# MSG_YES
#yes
!si

# MSG_NO
#no
!no

# MSG_YES_NO
#Yes - X / No - O
!Si - X / No - O

# MSG_ENABLED
#enabled
!habilitado

# MSG_DISABLED
#disabled
!deshabilitado

# MSG_SCALE_UNSCALED
#unscaled 3:2
!sin escalar 3:2

# MSG_SCALE_SCALED
#scaled 3:2
!escalado 3:2

# MSG_SCALE_FULL
#fullscreen 16:9
!completa 16:9

# MSG_SCN_OPT1
#option 1
!opcion 1

# MSG_SCN_OPT2
#option 2
!opcion 2

# MSG_FS_AUTO
#automatic
!automatico

# MSG_FS_MANUAL
#manual
!manual

# MSG_FS_OFF
#off
!off

# MSG_FS_UNIFORM
#uniform
!uniforme

# MSG_FS_RAMDOM
#random
!aleatorio

# MSG_SB_2048
#2048 bytes
!2048 bytes

# MSG_SB_3072
#3072 bytes
!3072 bytes

# MSG_SB_4096
#4096 bytes
!4096 bytes

# MSG_SB_5120
#5120 bytes
!5120 bytes

# MSG_SB_6144
#6144 bytes
!6144 bytes

# MSG_SB_7168
#7168 bytes
!7168 bytes

# MSG_SB_8192
#8192 bytes
!8192 bytes

# MSG_SB_9216
#9216 bytes
!9216 bytes

# MSG_SB_10240
#10240 bytes
!10240 bytes

# MSG_SB_11264
#11264 bytes
!11264 bytes

# MSG_SB_12288
#12288 bytes
!12288 bytes

# MSG_BK_EXITONLY
#Exit only
!Solo salir

# MSG_BK_AUTO
#Automatic
!Automatico

# MSG_CLK_33
#33MHz
!33MHz

# MSG_CLK_66
#66MHz
!66MHz

# MSG_CLK_100
#100MHz
!100MHz

# MSG_CLK_133
#133MHz
!133MHz

# MSG_CLK_166
#166MHz
!166MHz

# MSG_CLK_200
#200MHz
!200MHz

# MSG_CLK_233
#233MHz
!233MHz

# MSG_CLK_266
#266MHz
!266MHz

# MSG_CLK_300
#300MHz
!300MHz

# MSG_CLK_333
#333MHz
!333MHz

# MSG_SS_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%04d_%02d_%02d_%s%02d_%02d_%02d_%03d
!%04d_%02d_%02d_%s%02d_%02d_%02d_%03d

# MSG_SS_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%s%02d_%02d_%04d_%02d_%02d_%02d_%03d
!%s%02d_%02d_%04d_%02d_%02d_%02d_%03d

# MSG_SS_FMT_3
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%s%02d_%02d_%04d_%02d_%02d_%02d_%03d
!%s%02d_%02d_%04d_%02d_%02d_%02d_%03d

# MSG_ERR_BIOS_1
#Sorry, but gpSP requires a Gameboy Advance BIOS image to run\n
#correctly. Make sure to get an authentic one (search the web,\n
#beg other people if you want, but don't hold me accountable\n
#if you get hated or banned for it), it'll be exactly 16384\n
#bytes large and should have the following md5sum value:\n\n
!Lo sentimos, pero gpSP requiere una BIOS de Gameboy Advance para ser ejecutado\n
!correctamente. Asegurate de que sea autentica (busca en internet,\n
!ruega a alguien si quieres, pero no me hagas responsable\n
!si te enfadas), ocupara exactamente 16384 bytes\n
!y deberia tener el siguiente valor md5sum:\n\n

# MSG_ERR_BIOS_2
#a860e8c0b6d573d191e4ec7db1b1e4f6 or 1c0d67db9e1208b95a1506b1688a0ad6\n\n
#Other BIOS files might work either partially completely, I\n
#really don't know.\n\n
#When you do get it name it gba_bios.bin and put it in the\n
#same directory as this EBOOT.\n\n
#Good luck. Press any button to exit.\n
!a860e8c0b6d573d191e4ec7db1b1e4f6 o 1c0d67db9e1208b95a1506b1688a0ad6\n\n
!Otras BIOS podrian trabajar parcial o completamente, no\n
!lo se.\n\n
!Cuando la consigas renombrala a gba_bios.bin y ponla junto al\n
!EBOOT.\n\n
!Buena suerte. Pulsa cualquier boton para salir.\n

# MSG_ERR_BIOS_MD5
#This BIOS is not regular.\n
#There is a possibility of various trouble.\n\n
#Please use regular BIOS.\n
!Esta BIOS no es autentica.\n
!Podrian ocurrir varios problemas.\n\n
!Por favor usa una BIOS autentica.\n

# MSG_R_4_3
#ratio 4:3
!escala 4:3

# MSG_R_16_9
#ratio 16:9
!escala 16:9

# MSG_I_NON
#progressive
!progresivo

# MSG_I_ON
#interlace
!entrelazado

# MSG_INIT_END
#Initialization end
!Fin Inicializacion

# MSG_LOAD_STATE
#Load State.
!Carga Partida.

# MSG_LOAD_STATE_END
#Load State End.
!Partida Cargada.

# MSG_SAVE_STATE
#Save State.
!Salva Partida.

# MSG_SAVE_STATE_END
#Save State End.
!Partida Salvada.

# MSG_LOAD_STATE_No
#Load State No: %d
!Load State No: %d

# MSG_SAVE_STATE_No
#Save State No: %d
!Save State No: %d

# MSG_LOAD_ZIP_ROM
#Load ZIP ROM.
!Load ZIP ROM.

# MSG_LOAD_ROM
#Load ROM.
!Load ROM.

# MSG_LOAD_ROM_OK
#Load ROM OK.
!Load ROM OK.

# MSG_CHEAT_MENU_5
#Cheat page: %d
!Pagina de trucos : %d

# MSG_CHEAT_MENU_HELP_5
#Cheat page
!\n\n\n\n
!Pagina de trucos

# MSG_CHEAT_MENU_6
#Enable HOME: %s
!Habilitar HOME  : %s

# MSG_CHEAT_MENU_HELP_6
#Enable HOME
!\n\n\n\n
!Habilita HOME
