@echo off
bdf2bmp -s1 -c16 ../../bdf/5x10a.bdf 5x10a.bmp
bdf2bmp -s1 -c16 ../../bdf/5x10B.bdf 5x10B.bmp
bdf2bmp -s1 -c16 ../../bdf/5x10rk.bdf 5x10rk.bmp
bdf2bmp -s1 -c16 ../../bdf/batang10.bdf batang10.bmp
bdf2bmp -s1 -c16 ../../bdf/eureka.bdf eureka.bmp
bdf2bmp -s1 -c16 ../../bdf/cp1251.bdf cp1251.bmp
bdf2bmp -s1 -c16 ../../bdf/knj10.bdf knj10.bmp
bdf2bmp -s1 -c16 ../../bdf/knj10B.bdf knj10B.bmp
bdf2bmp -s1 -c16 ../../bdf/maru10.bdf maru10.bmp
bdf2bmp -s1 -c16 ../../bdf/min10.bdf min10.bmp
pause